### ISSUE TITLE
Description Format (Paragraphs) Are Ignored After Submitting An Order

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1085]
When creating a marketplace listing, adding bulletpoints to the full description won't be reflected in the description box in the SELL page. Example here: 
<img width="693" alt="screen shot 2018-06-29 at 4 22 57 pm" src="https://user-images.githubusercontent.com/27031337/42117426-5bb47f90-7bca-11e8-9151-6f2d5133eccc.png">

In this picture, all the black squares were initially bulletpoints, meaning each square was supposed to be on its own line, and there was a total of 3 paragraphs. Instead, it was reformated after submitting the listing into one single paragraph. 

This is important that the line keeps separated and that they do not form into one big paragraph as vendors will often make bulletpoints for features and specs on their items.

**Comment by HenkSwardt** [comment]
Issue has been logged:

https://particl.atlassian.net/browse/PD-289

**Comment by AllienWorks** [comment]
@cryptoguard just out of curiosity - how did you achieve this? Did you have this written somewhere else (Word etc.) and then copy-pasted it to PD?

Because it looks like some weird macOS-specific stuff (these are not classic list bullets) - looks more like emoji or something like that..

**Comment by zaSmilingIdiot** [comment]
Could be that it was copied/pasted from somewhere... the characters seem to be correctly persisted though between the creation of the listing and the display of the listing, at least according to the original issue. 

@AllienWorks Would the problem here not be related to the display/rendering of line feeds? Specifically, the code could either be stripping them out when performing a post, or stripping them out prior to rendering them, or not correctly converting the specific characters to appropriate `<br>` or `<p>` type elements, or just not accounting for various CR/CRLF/LF combinations.

**Comment by kewde** [comment]
@Allien
https://www.w3schools.com/cssref/tryit.asp?filename=trycss_text_white-space

add CSS 
```
white-space: pre;
```

**Comment by AllienWorks** [comment]
@kewde you just beat me to CSS. It actually works (even if `white-space: pre-line;`)

> /me ashamed

**Comment by kewde** [comment]
I remembered struggling with this a few years back, I know that \n isn't interpreted as line breaks.
Had to look up how though :)

**Comment by cryptoguard** [comment]
> @cryptoguard just out of curiosity - how did you achieve this? Did you have this written somewhere else (Word etc.) and then copy-pasted it to PD? Because it looks like some weird macOS-specific stuff (these are not classic list bullets) - looks more like emoji or something like that..

I copy-pasted from a classified ads website :P Might be that it can't be done.

**Comment by zaSmilingIdiot** [comment]
Has been merged into market, so resolving the issue.
