### ISSUE TITLE
Should Automatically Reject Listing Attemps When not Enough Coins & Notify User

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1101]
When trying to publish a listing, when clicking the Publish button, Particl Desktop should automatically reject the listing attempt if the user doesn't have enough coins to cover the insurance cost of the MAD escrow. The user should be notified that it doesn't hold enough coin to support the escrow of the transaction.

**Comment by zaSmilingIdiot** [comment]
Given that anything can change between the time the seller lists a posting and a buyer attempts to bid on the listing **and** the seller accepts the bid (remember that the seller can wait an amount of time before accepting a bid), I don't see it being necessary to have such restrictions on the seller at the time of listing creation. 

For example: if a bid is accepted, the seller needs the funds to cover their portion of the escrow at that point in time. If they don't have enough, they may transfer funds to their current wallet to do so (perhaps holding additional funds in a secondary wallet).
Further,  consider a scenario in which nobody bids on a particular listing, which means that the seller has been forced to have funds available for no particular reason.

Finally, such a requirement is easily worked around - the seller simply ensures "extra" funds are available in order to post the listing (to ensure compliance with this requirement) and then transfers the "extra" funds out after the posting is successfully completed.

So all in all, this requirement seems to introduce complexity that makes the seller experience more of a potential annoyance without providing any real benefit to either the buyer or seller. Hence, I'm going to close this request off; it can be re-opened if there is further interest in such a feature.
