### ISSUE TITLE
Community Proposal Display in Overview

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1137]
This is how published community proposals are indicated in the overview page:

**Display:**
<img width="625" alt="screen shot 2018-09-10 at 3 24 54 am" src="https://user-images.githubusercontent.com/27031337/45282549-3ebf5780-b4a9-11e8-844d-fb85b19f23da.png">

**Expanded:**
<img width="622" alt="screen shot 2018-09-10 at 3 25 02 am" src="https://user-images.githubusercontent.com/27031337/45282548-3ebf5780-b4a9-11e8-9f76-58636483d1df.png">

Would be more useful to name the display **Proposal Published** instead of **Posted Listing**
Also, when expanding the box, would be useful to have the proposal ID, number or key displayed instead of a grey text box. Will help keep track of records for the user.

**Comment by HenkSwardt** [comment]
Thank you for the feedback, we will look into this.

**Comment by zaSmilingIdiot** [comment]
The creation of both listings and proposals are essentially performed by sending an smsgmessage, and the user is paying a transaction cost on the message rather than creating a direct blockchain transaction; ie: the sending of the message is a transaction on the blockchain, rather than creating a direct transaction itself.

What we see from the system is a smsgmessage being sent, for both cases, without a means of identifying the nature of the message in the transaction itself. Complicated solutions do exist, such as storing the transaction ID in the marketplace for each specific type of paid message sent, and then looking up into this list for each wallet transaction. This is somewhat non-performant, and a little more complicated to implement. 

A longer term solution for this is being considered. However, in the meanwhile, we are looking at the much simpler solution of updating the label in the wallet. See https://github.com/particl/particl-desktop/pull/1523 . Until the "longer term solution" is ready to be implemented, this label change update will need to serve as the interim solution.

Obviously, community related changes are welcome, and if a solution is proposed then we can definitely look at merging it in.
