### ISSUE TITLE
Community Proposals Text Formatting Issue

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1148]
<img width="684" alt="screen shot 2018-09-14 at 3 43 08 pm" src="https://user-images.githubusercontent.com/27031337/45571686-06b36e00-b835-11e8-8ede-0e639e725fb5.png">

Formatting for the text is wrong. There's no spacing, similar to a previous issue with listing previews. The text was initially formatted as follow: 

> ...be able to use the marketplace first? 
> 
> 1) A web gateway/website (i.e. marketplace.particl.io)
> 2) A mobile application

**Comment by zaSmilingIdiot** [comment]
Appears to be related to #1085 despite that issue specifically referring to listings and this to proposals. 

A test with the latest market branch codebase (which includes the fix from #1085), shows this issue to have already been fixed. However, just to make 100% certain, would it be possible to confirm:

1. Whether the listings issue is fixed in the build you are currently using;
2. The OS that this behaviour was viewed on;
3. The source of the input text if the proposal was created by yourself (eg: copied from another site or document, input directly into the 'Proposal description' input box, etc).

**Comment by cryptoguard** [comment]
> 1. Whether the listings issue is fixed in the build you are currently using;
It appears that it is fixed

> 2. The OS that this behaviour was viewed on;
MacOS

> 3. The source of the input text if the proposal was created by yourself (eg: copied from another site or document, input directly into the 'Proposal description' input box, etc).
On the initial issue (#1085), the text had been copied from a classified ads website and not edited. On this issue though, the text has been written directly from within Particl Desktop with the correct formatting (at the moment of writing, but did not display correctly).

**Comment by zaSmilingIdiot** [comment]
And this is not fixed in the newest test build by any chance?

**Comment by HenkSwardt** [comment]
Please see tests on formatting of proposals:

![image](https://user-images.githubusercontent.com/28799964/45668632-cfd3a580-bb1d-11e8-919d-9a7a8573368e.png)

![image](https://user-images.githubusercontent.com/28799964/45668643-dfeb8500-bb1d-11e8-8e67-822a19eae8cb.png)

**Comment by cryptoguard** [comment]
Yes, it is fixed :D
