### ISSUE TITLE
Category Dropdown Menu Styling Enhancement Proposal

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1155]
Right now, when selecting a category this is what the dropdown menu looks like: 
<img width="294" alt="screen shot 2018-09-19 at 9 56 27 pm" src="https://user-images.githubusercontent.com/27031337/45791323-2a245180-bc57-11e8-9aae-ec129b9c621f.png">

I was thinking perhaps it could be easier to navigate through the menu if all categories were collapsed, and only expanded once you click on it. Not sure if it is possible within a dropdown menu though...

So for example, in the screenshot above, instead of having (in order) the following when opening the dropdown menu: 
- Particl
- - Free Swag
- High Values
- - Business / Corporate
etc

You would have: 
- Particl
- High Values
etc

and only once you click on High Values would "Business / Corporate", as well as the other sub-categories for High Values, would show up. This would make it easier to choose the right category and make navigating through the options less of a hassle.

**Comment by kasprrr** [comment]
To add to this, whenever a user presses the letter K, U or whatever on its keyboard, categories/countries starting with that specific letter should come up automatically (fairly standard drop-down behavior). Right now this is not the case

**Comment by HenkSwardt** [comment]
Hi @kasprrr 

Can you please provide me with your versions of the GUI as displayed at the bottom left corner of the Application as well as operating system details.

Reason I'm asking, we added this behavior to allow for hot searches a while back and it is working on my side. Please see below:

Countries:

![image](https://user-images.githubusercontent.com/28799964/45939878-02761600-bfd6-11e8-88c0-7c4de362b6b8.png)


Categories:

![image](https://user-images.githubusercontent.com/28799964/45939898-22a5d500-bfd6-11e8-82d1-012107207ab1.png)

**Comment by zaSmilingIdiot** [comment]
@kasprrr Do you have any feedback for us on this?

**Comment by zaSmilingIdiot** [comment]
@cryptoguard Thanks for the suggestion. We are currently looking into completing the suggested menu behaviour.

**Comment by HenkSwardt** [comment]
For now we have added a tooltip on hover to display any characters that might not fit into the display space, 
Please see: 
https://particl.atlassian.net/browse/PD-363
https://github.com/particl/particl-desktop/pull/1176

We also added a task to further add the ability to expand and collapse the main categories, giving you a more detailed view of all main categories. 
Please see: 
https://particl.atlassian.net/browse/PD-436

**Comment by kasprrr** [comment]
Sorry for not getting back to you guys earlier.
So what i meant is that, for example, typing in "ne" brings up the following:
![ne](https://user-images.githubusercontent.com/37086658/46764426-a0860380-cc99-11e8-92cd-d110298ed58c.png)


Why is "Brunei" the first filtered country instead of "Nepal" / "Netherlands"? This is confusing to me.

0.0.42 market

**Comment by kasprrr** [comment]
So for a dropdown such as "Country" first letter filter seems the way to go, for other dropdowns such as "Category" you may want to keep current filter system

**Comment by zaSmilingIdiot** [comment]
@kasprrr the dropdown options are filtered by any sequence of the characters matching the input text. And then ordered alphabetically. So as per your example, all of the filtered countries contain the letters "ne" in them, and then are displayed in the order shown due to being sorted alphabetically. Which is why Brunei appears before Netherlands.

It does however, make sense to filter the countries by a case-insensitive match that starts from the first sequence of input characters. As you suggest. This will mean that inputting 'n' will filter the options to those starting with the letter 'n'. We can add a feature request for this... as suggested, this should only be applicable to the country selection. @HenkSwardt can you please assist in creating the necessary JIRA ticket?

**Comment by btmr** [comment]
@cryptoguard Reducing the amount of white space between the lines would also help to make the menu easier to read and navigate.
Collapsing the categories is a good idea. I don't mind the extra clicks because they provide a feeling of having control. Besides, a tidy menu is less exhausting to look at.

**Comment by zaSmilingIdiot** [comment]
The original reported issue has been resolved, as the Categories menu is now a collapsible dropdown list.
The additional request to filter country dropdowns by a case-insensitive match that starts from the first sequence of input characters only, has also been previously completed.

Closing this as implementation for both requested enhancements is complete.
