### ISSUE TITLE
Total amount send/receive tab missing

### ISSUE THREAD

**Issue by TzeKraken** [particl/particl-desktop#1194]
# Total amount send & receive tab is missing

After downloading the latest testnet build I found out that the total amount present in the wallet is not displayed in the send or receive tab and only in the wallet overview tab.
Is there any specific reason why this is left out? I would recommend adding the total amount  contained in the send/receive tab of the wallet, I think it would benefit the users experience.
![send](https://user-images.githubusercontent.com/43935073/47036754-70e56880-d17d-11e8-9583-4197fb2b4c1d.jpg)

# More information

- Windows 7 Ultimate 32-bit
- Client 1.2.2-alpha-RC1

**Comment by zaSmilingIdiot** [comment]
Thanks for mentioning this. There is no specific reason the totals were not included in these 2 pages, but in saying that, there does not appear to be an actual use case/benefit to the user's current intention when using one of those 2 pages. Specifically:

- in the wallet > receive page, there does not appear to be an obvious reason why the total balance in the wallet would be available... the intention/use-case here is to obtain the details for receiving a payment and knowing the total balance in your wallet has no impact on your ability to obtain an address to receive funds.

- in the wallet > send page, the totals available for each type of 'Public/Particl', 'Blind' and 'Anon' are displayed (right hand side section just below each type). Again, the activity of sending funds from a particular type requires knowing how much is available in that type; there doesn't appear to be much use for an overall total.

- The overview page functions in a manner that provides a wallet summary, which would require the total value to be displayed (hence its inclusion in the overview page).

So in order to understand this request properly, would it be possible to provide a use case or reason for the displaying of an overall total in these pages? It would be helpful for us to understand where the user benefit occurs.

**Comment by zaSmilingIdiot** [comment]
I'm closing this due to lack of information at the moment (it can always be re-opened later when feedback is available).
