### ISSUE TITLE
message : Wallet is currently rescanning. Abort existing rescan or wait

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1205]
# Describe bug/issue

When you click on "Continue on this picture" during the process of creation of the wallet this message can appear. And it's hard to understand what it means and what you should do.

<img width="583" alt="wallet is currently rescanning" src="https://user-images.githubusercontent.com/44212051/47113469-6ef0d780-d259-11e8-8b96-b91b921b8e11.PNG">

The message "Wallet is currently rescanning. Abort existing rescan or wait"

I really didn't understand what it means so i tried to go back which is not allowed ect ... after few seconds wallet is successfully created.

The message should be something like that "Your wallet is being created - Wait here"

# How to reproduce

1. try creating a wallet for the first time right after launching the Desktop.exe

# More information

- Operating system and version: Windows 10
- Client version: 1.2.2-alpha-RC1

**Comment by HenkSwardt** [comment]
Good day @michmish 

This is expected behavior from the client as far as I am aware. That is a warning message to indicate the wallet is busy with a scan and cant perform the request. It will accept the request as soon as the scan is complete. Normally takes around 20 to 30 seconds.

@zaSmilingIdiot , Can you also confirm this please. Maybe we can made the message more user friendly?

**Comment by zaSmilingIdiot** [comment]
The message is the response from the daemon. We can most certainly make it a little more user friendly, particularly since we're not providing the 'abort existing rescan' option directly in the GUI. We can likely provide this option if its something that is required, but for now perhaps starting with just updating the informative message (instead of using the daemon provided response directly).

**Comment by zaSmilingIdiot** [comment]
@HenkSwardt Could you perhaps create a task for us for this please.

**Comment by HenkSwardt** [comment]
Task logged to address this issue:

https://particl.atlassian.net/browse/PD-464

**Comment by zaSmilingIdiot** [comment]
The wallet scanning message has been updated to be a little more user friendly and be a little more accurate with regards to informing the user what is currently occurring.

Change occurred in https://github.com/particl/particl-desktop/pull/1265
