### ISSUE TITLE
Improvement of Multisig / Escrow Label in Overview Page

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1240]
Currently, when funding an escrow smart-contract, the overview page shows as this: 

<img width="639" alt="screen shot 2018-11-09 at 1 42 54 pm" src="https://user-images.githubusercontent.com/27031337/48281722-7608a100-e425-11e8-950e-b8823b267507.png">

To be a bit more user-friendly, the label could simply display "Escrow Contract" and drop the "multisig" part which, for regular users, don't mean much (mainstream doesn't know what it is).

**Comment by GBen1** [comment]
On cryptoguard picture, we can see -15 PARTS but the buyer only paid 10PARTS for the escrow. 15PARTS are the amount for the buyer escrow + the seller escrow. It can be confusing when you are the buyer or the seller to see the total amount of the escrow on this line instead of what they really paid ( as it happened to litebit during his last AMA).

**Comment by zaSmilingIdiot** [comment]
@GBen1 This problem has been corrected in the latest releases, and can be confirmed in the v2.0.0-alpha pre-release version at least.

**Comment by zaSmilingIdiot** [comment]
Can be confirmed at least in the v2.0.0-alpha1-testnet release :)
