### ISSUE TITLE
Particl Desktop Eats ~1Gb Memory After a Few Days (Memory Leak?)

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1252]
OS: MacOS 10.14
Client: 
<img width="247" alt="screen shot 2018-11-12 at 7 46 48 pm" src="https://user-images.githubusercontent.com/27031337/48383609-736fab00-e6b4-11e8-9733-17cb811ecb18.png">

When first launching Particl Desktop, here's the memory space it's taking: 
<img width="427" alt="screen shot 2018-11-12 at 7 53 33 pm" src="https://user-images.githubusercontent.com/27031337/48383666-add94800-e6b4-11e8-9e4a-e9708b78382d.png">

After having the client up for a few days, here's the memory space it then takes:  
<img width="425" alt="screen shot 2018-11-12 at 7 49 45 pm" src="https://user-images.githubusercontent.com/27031337/48383679-c184ae80-e6b4-11e8-9df6-018081b4d041.png">

That's **roughly 1,250 MB**. Possible memory leak?

**Comment by zaSmilingIdiot** [comment]
Bug fixes have been implemented since v2.0.0 launch to improve memory related issues.

One possible cause of such a significant leak is opening dev tools with debug logging enabled, and leaving that open for a significant amount of time. But barring that potential issue (which is not something specific to the particl-desktop application), the issue for such a significant leak should have since been resolved within the fixes for memory leaks and other bug fixes that have been applied since the issue was raised.
