### ISSUE TITLE
Listings tab doesn't automatically refresh after syncing chain is completed (win10)

### ISSUE THREAD

**Issue by kasprrr** [particl/particl-desktop#1257]
Describe bug/issue
Viewing the Listings tab doesn't seem to automatically update the listings to retrieve new ones after chain synchronization is just completed. Listings are added to the listing page, but i may have to leave the listings tab and navigate back to it to see new ones, especially when there are multiple new ones. It seems it takes the client a little while to load the new listings and the page doesn't automatically refresh. I have to leave the listing tab and re-navigate back to it for new ones to occur. If i wait for a minut or so after the chain sync has been completed, all listings will be there whenever i leave the listing tab and navigate back. However, when i leave and navigate back within 5 to 10 seconds, only some of the new listings are loaded. I need to wait another 5 to 10 seconds (and leave/navigate back) in order to see more. This all occurs after the chain has already been sycned. 

More information
Operating system and version: Windows 10
Client version: 0.0.45, 0.17.0.1, 1.2.2 alpha RC1

**Comment by zaSmilingIdiot** [comment]
The source of the issue here is that on startup, the marketplace is still busy processing/updating all of the received messages to extract the relevant item information. The items that are available are displayed to the user such that the user has something to browse. 

At present, the listings page does not automatically refresh the listings. Which we could possibly do, but there is the use case to consider that the user is busy scrolling through the listings already available, and automatically inserting new listings at the top of the page results in unwanted automatic page scrolling or listing shuffling (thanks @HenkSwardt for pointing this use case out). This is a side effect of using the infinite scroll "pagination". 

So we don't want to be automatically inserting new items as they become available, but we need to allow for the user to obtain newly received listings, without needing to navigate away from the listings page and back again to do so. The simplest solution here is to allow for the user to decide when to "refresh" the listings page by providing a button ont he listings page that reloads the listing information. So essentially providing a means to update the listing items without needing to navigate around the app to do so. This is the basis of the change applied here: https://github.com/particl/particl-desktop/pull/1313

**Comment by DrDBanner** [comment]
I came to the same on the latest Testnet 201902051520 Client and identified this as an UX issue. There should be no user interaction needed.

**Comment by zaSmilingIdiot** [comment]
I'm re-opening this as something to look into for the initial load of items: both as an issue 
1. for no listings being present after the chain syncing (requiring a restart of the application)  is complete and
2. when there are no listings to perhaps poll frequently until such time as there are listings.

Once some listings are displayed, then its up to the user to refresh the page when they deem it appropriate. 

The problem here is the use of infinite scrolling along with the display of 'newest items first' - when multiple "pages" of listings have been loaded, pushing one or more new listing items at the start of the list forces the loaded listings to adjust position. This would be terrible UX - as a user is about to select an item to view more details or add it to the cart, new items are inserted at the beginning of the loaded list and the specific item the user is interested in automatically adjusts and disappears further down the page.

The same scenario applies even if the user is browsing the first few items, so trying to trap when the user is at the top of the list of items, for example of a workaround, is somewhat pointless. One option might be to display the oldest listings first, such that newest items could be appended to the end of the list, and providing a workable solution. It tends to become tedious for buyers though wanting to see the latest listed items - they need to scroll past a potentially large set of listings that they have seen before to arrive at the latest listings. 

Hence why the refresh button currently exists - the user makes an explicit decision to load new listings. There is a change logged already to display a little notification on the refresh button to indicate that new listings are available. Which should make the refresh button a little more "applicable" in its usage.

**Comment by zaSmilingIdiot** [comment]
The explanation for the original issue of navigating back and forth between the listings page and another page to see listing items just after the chain has finished loading, has been explained.

A solution has also been implemented to include a refresh button, that allows one to refresh the listings page to display more listings. There is a need for the browsing user to initiate this action for reasons explained above. Additionally, the refresh button attempts to indicate when new listings are available to be displayed.
