### ISSUE TITLE
Listing details (description, escrow etc) absent in buy tab

### ISSUE THREAD

**Issue by kasprrr** [particl/particl-desktop#1285]
After i add my wanted item to the cart and go to the buy tab, there is no way to retrieve the description and escrow details of the item. I would expect to be able to click on the item in the buy tab for the details, however this is not the case.

I have to navigate back to Listings tab in order to retrieve this information and i should't have to.

**Comment by HenkSwardt** [comment]
Good day @kasprrr 

Thank you for logging this. 

With regard to displaying Escrow and Shipping costs, we do cater for this in the cart. If you go to the main listings page, there is an option at the top right of the screen that allow you to select your country. By having this selected the listings page prices will update to include the shipping price in the total, depending on Local to your selected county or international. 

This then also adds more detailed pricing to your cart/checkout process, where you now see the shipping total in the main cart view and a calculation/breakdown of item price, shipping price and escrow price in the last overview page before continuing with placing the order.   

I do however like the idea of having another look at the description, @zaSmilingIdiot, can we maybe see if it will be possible to display the description as a tooltip on hover?

**Comment by zaSmilingIdiot** [comment]
I think the general idea here is that in a number of e-commerce platforms, the basket contains a summary of the each item (not the full description, but then also a link back to the item listing in the store. That way a buyer can view the product details again if they want to, without the manual effort of finding the specific listing item again.

Instead of just the description on hover, I think a better idea might be to have a link next to each item in the basket (or even the item title), which when clicked on would display the entire listing item modal again, similar to having clicked the listing item on the main cart page). Your thoughts on that?

**Comment by HenkSwardt** [comment]
Thank you for the feedback, 

I think that will also fit in well.

**Comment by kasprrr** [comment]
"I think the general idea here is that in a number of e-commerce platforms, the basket contains a summary of the each item (not the full description, but then also a link back to the item listing in the store."

This exactly 👍

**Comment by zaSmilingIdiot** [comment]
Has been implemented a described above.
