### ISSUE TITLE
Large Horizontal Images Should be Resized

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1290]
<img width="180" alt="screen shot 2018-12-02 at 12 55 02 pm" src="https://user-images.githubusercontent.com/27031337/49343102-ca243100-f631-11e8-9463-13d984eb214b.png">

When publishing listings with wide images, the edges (left-right) get out of bound of the listing space in the general overview of all listings. See this screenshot: 

<img width="232" alt="screen shot 2018-12-02 at 12 53 11 pm" src="https://user-images.githubusercontent.com/27031337/49343061-48cc9e80-f631-11e8-880a-167a911e2236.png">

When opening the listing modal, however, the image is displayed correctly: 

<img width="1034" alt="screen shot 2018-12-02 at 12 54 02 pm" src="https://user-images.githubusercontent.com/27031337/49343072-70bc0200-f631-11e8-9a44-67b7a956c21b.png">

**Comment by kasprrr** [comment]
If you chance the aspect ratio of these images, they will turn out real ugly. I think current way of sizing and centering larger images is the way to go

**Comment by cryptoguard** [comment]
Maybe we could make them smaller instead? Agreed on the ratio.

**Comment by zaSmilingIdiot** [comment]
@cryptoguard The image in the overview page appears to be cut off because the aspect ratio is being maintained. The image is being wrapped over the space allocated to it. 
The logic around it works something like scaling the image such that if both of the dimensions are greater than the dimensions of the space in which to render it, then the image is scaled until one dimension matches the bounding rectangle. Keeping the aspect ratio the same, the other dimension (having been scaled appropriately) is then "cut off".

If the image is scaled until the bounding dimensions completely encompass the image, then that results in images that have one very long dimension in relation to the other dimension scaling proportionately to make the other dimension very small in the  bounding box. So for example, an image with a width 2x longer than the height would result in an overview image that would be the width of the image box but half the height of it. Which may make it difficult to determine what it is,  but it also introduces a significant amount of white space around the images, as most images are not likely going to match the aspect ratio of the bounding box exactly. Which means most images would have some white space around it.

While there is a bit of "cutoff" on some of these images, the current settings provide for the more visually appealing of displaying the images.
