### ISSUE TITLE
MP Listing: Disable listing of a whole vendor from individual user perspective

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1420]
[FETAURE REQUEST]

As soon as an individual "reports" an item as inappropriate this item should vanish from the individual listings page and give the user the option to flag a whole vendor as "Don't want to see him in my listings".

**Comment by HenkSwardt** [comment]
Good day @DrDBanner 

Thank you for assisting in with the test effort. 

At the moment all listings are individual and not grouped per Vendor. I do like the proposal though. This could be something we can look into in the future @xludx @zaSmilingIdiot 

With regard to the first part of your request "As soon as an individual "reports" an item as inappropriate this item should vanish from the individual listings page" 

Please see the response on https://github.com/particl/particl-desktop/issues/1419

Thank you

**Comment by zaSmilingIdiot** [comment]
@HenkSwardt We could add the ability to hide user-flagged items from the main listing as a feature request as well. So if the user themselves have flagged an item, then don't display it until they explicitly use the filter. The user has flagged the item and so likely does not want to view the listing.

**Comment by cryptoguard** [comment]
> @HenkSwardt We could add the ability to hide user-flagged items from the main listing as a feature request as well. So if the user themselves have flagged an item, then don't display it until they explicitly use the filter. The user has flagged the item and so likely does not want to view the listing.

Yeah, we definitely should. The logic behind this is that if you flag an item as inappropriate, then it is more than likely that you will not want to see it when browsing. For example, if I flag a porn listing as inappropriate, I sure don't want to still see it's listing picture when scrolling. 

So while my vote won't necessarily take the listing off of the marketplace, it will still make my own personal experience much more enjoyable because what I consider inappropriate from my personal point of view won't show up anymore after I flag them.

**Comment by cryptoguard** [comment]
Alternatively, maybe we could add a "hide" function that hides listings from your own point of view, but without flagging them? 

Same example, with a porn listing. I might want to hide these listings because porn listing pictures are annoying and NSFW, but that doesn't mean I necessarily want to vote them out of the marketplace. I don't want to see them, but I still don't mind other people buying and selling those.

**Comment by zaSmilingIdiot** [comment]
The hiding of flagged items has been implemented as of v2.0.0

The request to hide by vendor requires that vendors have some form of identity on the marketplace, and so can be discussed again once such a requirement in being tabled. Until then, this is not going to be possible.
