### ISSUE TITLE
Can't receive bid / send bidding, proposals voting seem incomplete

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1473]
# Describe bug/issue

Desktop fully synced, wallet 100% operationnal.

I think i can see every listing available. If i send a buy request, buyer never seem to receive it.
If i sell an item and someone bid on it, i never receive the bidding message.

I am right now unable to do any trade on marketplace testnet.

For proposals, i miss some proposals ... n°7 and n°8 for example and i only see my own votes on the proposals but i know some people put some more voting on those poll.

I don't know what i can provide to help reproduce or find how to solve this issue on my desktop testnet.

# How to reproduce

My desktop seems to be the only one in this situation, can't reproduce at will.

# More information

- Operating system and version: win64 - testnet20190220 build
- Client version:  0.0.51

**Comment by zaSmilingIdiot** [comment]
If wallet transactions appear to be working correctly (ie: sending/receiving from your wallet), then the problem is likely contained to the particl-marketplace section. In which case, it might be helpful to know whether the wallet used has been replaced since the marketplace was first set up? In other words, have yo uby any chance replaced the wallet.dat file without wiping the marketplace database?

**Comment by HenkSwardt** [comment]
Hello @michmish 

Could you please provide us with your MP logfile?

With regards to this "For proposals, i miss some proposals ... n°7 and n°8 for example and i only see my own votes on the proposals but i know some people put some more voting on those poll."

The voting on listing items for removal also use the proposal system in the back-end, but no proposal for these are shown. The 2 you don't see are most likely proposals related to items like these.

**Comment by michmish** [comment]
Hello guys,

@zaSmilingIdiot, wallet.dat didn't move on this testnet computer, it's still the same.
Only files that changed is the .lock (deleted to enable wallet launch - issue we saw together last week) in the Appdata/particl/tesnet repository.

@HenkSwardt, i will provide you or zaSmilingIdiot the MP logfile tonight on Riot in private message (not at home right now).

I stay available if you want me to do some listing creation so you can bid on it or if you want me to bid on some listings ... just to confirm the issue with fresh testcase

Thanks for the quick answer

**Comment by zaSmilingIdiot** [comment]
@HenkSwardt Thats applicabel for voting on listing items... the original issue mentions proposals that are not visible.

**Comment by michmish** [comment]
I can't check if if my votes for listing removal are taken into account on the marketplace anyway. It would be interesting if there is a way to confirm this additional issue.

About Proposals n°7 and n°8 not showing : another possibility is that they are expired so they disapeared ... but even if that's the case i should have been able to see them in the "Past Proposal" category in desktop

**Comment by c3lopetra** [comment]
hi guys,
@zaSmilingIdiot @HenkSwardt
i ran into a similar problem yesterday, checking out the buy- and sell-flow on the latest builds.
I´m running a mac, latest osx.
I published two listings, mich was bidding on them, but i didn´t saw his bid. Mich couldn´t see my offers as well, bidding on his listings. we couldn´t trade on the marketplace.
I had several testnet builds on this machine, but restored my wallet through the mnemonic. I could still see other listing, bids and offers, i had on previous testnet builds. therefore i checked my libraries and found other testnet folders which were still existing.
I wiped everything. I wanted to report it because we both could see the respective listings from the other and could still bid on it. i created a proposal, mich could participate and we were able to send funds to each other.
After i wiped everything now half of my balance is gone, but the history is still accounting for the missing parts.
I also tried to find a listing from part-linux and i don´t see it, and mich can´t accept my offer after wiping all existing folders and a full resync.

**Comment by c3lopetra** [comment]
sorry guys, it seems to work now. buy- and sell-flow is working smooth. problem was on my end... had to wipe all existing folders, there were different ones, and i simply forgot to delete them all.

still 500 t parts missing tho.

**Comment by zaSmilingIdiot** [comment]
The problem with missing details is likely related to marketplace DB writes failing. There is a potential fix to address this: https://github.com/particl/particl-market/pull/377

**Comment by zaSmilingIdiot** [comment]
Missing buy flow messages should now be resolved: see particl/particl-market#377 and https://github.com/particl/particl-market/pull/386

The fixes will be available in the next marketplace version released.
