### ISSUE TITLE
Particl Desktop console commands to UI

### ISSUE THREAD

**Issue by jf20spiker** [particl/particl-desktop#1527]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
I was trying to change my encryption password and I saw a console command. Couldn’t figure out the syntax. Would be nice to have a number of these console commands in a help menu in the app
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..
2. ..

# More information

- Operating system and version:
- Client version:

**Comment by zaSmilingIdiot** [comment]
By attempting to change your encryption password, I'm making the assumption that yo uare requesting the daemon rpc commands.

These daemon rpc commands can be viewed and executed via the 'Debug Console', accessible in Particl Desktop on the top right of the application. In the resulting window, ensure that the 'Core console' tab is selected (it should be by default), and then type `help` into the text box for a list of daemon rpc commands. You can also type `help <command>` to see more detailed information about a specific command.

The daemon configuration flags, which can be passed to the Particl Desktop when it starts up (typically via single dash flags, eg: `$ ./particl-desktop -testnet` where -testnet has a single hyphen in front of it), are a property of the particl daemon, and may change depending on the version of the daemon used. The majority of them are defined as a part of the bitcoin daemon though, and so most of the following should be available for example:
https://en.bitcoin.it/wiki/Running_Bitcoin#Command-line_arguments

As a reminder, note that startup flags do not permanently set the flags. To use the particular flags each time the daemon starts up, you would need to either pass the same flags each time (eg: starting up the particl-desktop with the same flags each time), or otherwise set the particl.conf file correctly.

Also keep in mind that, for the specific example you've mentioned about setting passwords, that on unix-type environments you might not want to set passwords via the terminal unless you are certain that the inputs typed in are not being stored in your terminal history. Better to be safe :D

Does that answer the question correctly?

**Comment by zaSmilingIdiot** [comment]
Closing... can be re-opened if necessary
