### ISSUE TITLE
Add an X to quit wallet creation

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1570]
During the wallet creation or import process, would be useful to add an X or some option to quickly exit the process without having to click several times on the < Back button. 

<img width="1440" alt="Screen Shot 2019-04-11 at 9 25 31 PM" src="https://user-images.githubusercontent.com/27031337/56005863-953f7f00-5ca0-11e9-9067-d9b81b848546.png">

**Comment by zaSmilingIdiot** [comment]
I'm not quite certain that this would be helpful.

Generally, the wallet creation/restore process consists of at least 3 'milestones' in order to generate/restore a wallet (with 2 at least being required). Once one of the milestone steps have been completed successfully, we do not navigate back to the corresponding step, skipping over it whichever way the user navigate the process steps. For example, once a wallet is named successfully, the wallet naming step is skipped over for this particular wallet.

In saying that we use the 'Cancel' button mostly for convenience in case of user error:
- The 'Cancel' button between the steps allows for the user to navigate back to previous steps for convenience. For example, they forgot to take proper note of the mnemonic in the 'Create wallet' process/flow. Or for the change of a recovery passphrase, as another example. Or even to change the flow, as the 'Create wallet' option may have been selected but the 'Restore wallet' was what was actually wanted.
- The 'Cancel' button on the process/flow selection step (step 1), allows the user to navigate back to the main application in case of error selecting the wallet setup option (whether selecting a wallet that was not completely set up previously, or the New Wallet button was accidentally used. It provides a means to navigate back to the main application.

With the above in mind, it would be preferable that a wallet setup is completed if it is started and actively continuing. Cancellation already is available from the first step (as mentioned above). Once a choice of setup flow is made, its one step back to the first step to cancel the setup process.That is maybe a little inconvenient, but not unlike most application setup wizards for example (which requires at least 2 steps to close the setup part-way through). Once progression has gone past the second step, the wallet should probably be completed in terms of setup. Providing an easy escape from within each step does little to drive this.

Is there a reason that a user would want to quickly abort the setup process part way through, but still continue with the application use in general afterwards?

**Comment by PARTimprovert** [comment]
I noticed this myself, just logged an issue but see cryptoguard already logged it. This is a ux mistake. Making the user go back through multiple screen which are irrelevant if someone wants to just close the wallet creation is odd and not user friendly. just textbook ux stuff, needs a fix imo.

**Comment by AllienWorks** [comment]
`Cancel` button here doesn't make sense, I agree with Arnold that it's irrelevant. Since you explicitly chose to follow this wallet creation/restoration wizard, I don't see a reason why you would like to cancel it in the middle. Are you creating new wallets just out of boredom? :)

> This is a ux mistake. 
> just textbook ux stuff, needs a fix imo.

Thanks for a solid feedback. Maybe add some reasoning behind this?

**Comment by zaSmilingIdiot** [comment]
I think the possible confusion here occurs in the thinking that all the information for creating the wallet is collected and then only at the end of the process the wallet is actually created. In which case, having a cancel button as part of the workflow that immediately aborts the data collection portion of it makes somewhat sense.

However, the current workflow is that the wallet itself is technically created immediately after providing a name for it. Hence, each step that you are completing is typically actually performing a specific action. Which is why when aborting part way through the wallet creation process, and attempting to re-complete the process, the user is explicitly moved over steps that have already been completed. Because the wallet already has been "initialized" with that particular information.
In this case, a cancel button part way through makes little sense.

Hope that helps clarify things a little bit.

**Comment by zaSmilingIdiot** [comment]
I'm going to close this as "wont fix" for now, based on my previous comment. If and when we change the workflow to first collect all the information before starting any processing, then this can (and will likely) be re-visited.
