### ISSUE TITLE
Bring back the loading bar progress : block synce

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1574]
New user have to know that it is normal that it takes time to create the first wallet (syncing the whole particl blockchain). Otherwise they will close it thinking it's stuck (can take 30min+ in wifi)

![20190411_225424](https://user-images.githubusercontent.com/44212051/56068262-79aaa600-5d7e-11e9-8c4d-654c1fe4e150.jpg)

**Comment by HenkSwardt** [comment]
Thank you for raising this, We will investigate. 

The normal preparing of the wallet should be rather quick (2 Minutes Max) However, the syncing should happen in the background after the wallet has been launched, This used to be indicated by a modal that the user could hide in the background, allowing them to monitor or bring back up from the left bottom corner. 

This modal is still in place but not being launched by default. The same indicator is still in place in the bottom left corner of the wallet.

**Comment by zaSmilingIdiot** [comment]
The wallet creation process is not typically dependent on the syncing of the blockchain. On some machines, and depending on whether encryption was selected or not, this wallet creation and setup process can take some time to complete. 
However, there is no determinate way to see progress. Hence the spinner that indicates something is happening. But this means that we cannot show a progress bar, since we cannot know how far along the process is, or rather how much outstanding progress there is.

Closing this as "Wont Fix"
