### ISSUE TITLE
Closing the application leaves an icon in taskbar, clicking it gives a javascript error

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1598]
Closing the application leaves the Particl icon for another 15 to 20 seconds active in taskbar (the one on the right where time/wifi is displayed etc). When clicked, the application returns the following error:

![jv - Copy](https://user-images.githubusercontent.com/49277632/61031866-ee7b9380-a3f2-11e9-8e12-df064fb637ba.jpg)

win 10 x64
Latest Alpha Blind 2.0.0

**Comment by zaSmilingIdiot** [comment]
This issue was closed automatically as an update to the shutdown process of the application has been made which resolves this issue. This update should be available in the next version release (ie: either as an update to v2.3 or v2.4)

The update ensure that the system tray is removed when the application begins the closing process and ensures that the reported behaviour cannot occur.
