### ISSUE TITLE
Change "Buy" in menu into "My Orders"

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1614]
"Buy" in the left menu should be changed into "My Orders". "Buy" is very confusing when there is "Listings" as well. 

It should be: Listings, My Orders, Sell (imo, much more clear to the user)

**Comment by zaSmilingIdiot** [comment]
"My Orders" is a somewhat ambiguous term: it can also refer to orders from a seller's perspective. I don't think this is a very good replacement term.

**Comment by PARTimprovert** [comment]
it is however far superior than "buy". I agree but you guys really need to find an alternative here. I think closing this issue was somewhat premature

**Comment by zaSmilingIdiot** [comment]
I'm re-opening this as a basis for a discussion on labelling changes; not just this particular instance, but others as well.

**Comment by zaSmilingIdiot** [comment]
Labelling has been updated as of v2.3.0 The menu now reads: Listings, Purchases, Sell.

Which appears to create less confusion, as the 'Purchases' corresponds more accurately to the act of what you have bought (or perhaps about to purchase, since the current cart is still visible in this page).

Other labelling has also been changed, particularly around the escrow status, to reflect exactly when the escrow transaction is made (it was previously confusing as the buyer would make payment and it would indicate that escrow is in effect already before the seller had actually made their escrow payment yet).
