### ISSUE TITLE
Market wallet gets restored as Default wallet

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1620]
I had a previous wallet named Market. I deleted it and all it's folders before downloading the latest release. When I first opened the Particl Desktop app, it asked me to create or restore a wallet. I selected restore and it skipped the Name Wallet part so I was not given the option to name this wallet. Therefore, when it restored, it showed up named as Default and no longer could access the market. 

Edit: I was able to "restore" that same wallet (using same 20-words) and name it Market this time (so now the same wallet exists simultaneously as Default and Market). But that seems like a weird way to manage this when people most likely will be restoring their Market wallet upon install.

**Comment by zaSmilingIdiot** [comment]
This is expected behaviour.

When setting up the very first wallet on a clean install, it is explicitly the default wallet that you are setting up. It is definitely possible to 'restore', using the mnemonic, to a wallet with a different name.

It is therefore possible to still create a 'market' wallet, and use the restore option to provide the same mnemonic and create the market wallet. In such a case, you'll end up with both the default wallet and the market wallet having the same transaction content.
