### ISSUE TITLE
If application is re-started after daemon did not shut down just yet, particl desktop hangs on initial loading screen

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1624]
#Describe bug/issue
If one decides to shut down/relaunch the application and not wait the 20 seconds the daemon needs to close properly, the launch screen of particl desktop would hang (quote screen). The application then needs to be restarted again and this starts the circle all over.

# How to reproduce
Quit application, restart right after (before daemon is shut down properly/icon in taskbar dissapears)

# More information

- Operating system and version: win10 X64
- Client version: latest testnet before mainnet

**Comment by zaSmilingIdiot** [comment]
This is to be expected. Core does take some time to shut down. If it is in the shutting down process, then attempting to connect to it again is going to result in an error: desktop is not able to start the core service up because it is already running, but also cannot get a connection to it as its it the process of closing.

There is an issue logged already for the desktop to attempt to connect to a running core instance, and that can likely be expanded to include the detail that if it cannot establish a successful connection, the desktop attempts a connection (and/or performs a core startup attempt) at applicable intervals.

Another, complimentary but distinct, option might be to wait for the core service to shutdown completely, and then close the GUI window. Displaying a 'we're shutting down now' window to the user. We can investigate such possibilities further going forward.

**Comment by zaSmilingIdiot** [comment]
Just noting that an update that caters for this has been applied, and should be in the next available release (likely an update to v2.3 or otherwise v2.4.0). Hence why this issue has been closed.

The update changes the startup/shutdown process of the application, which includes the GUI waiting for core to shutdown properly before actually closing, as well as enforcement of a single application instance.
