### ISSUE TITLE
Flagged Item wording

### ISSUE THREAD

**Issue by chunkingcheese** [particl/particl-desktop#1628]
I clicked the flag in the upper right hand corner for flagged listings. It says "Here is where you will find all publicly available listings for sale. " Should it be "Here is where you will find all flagged listings"?

Windows 10 

Particlmarket  testnet 2.0

**Comment by HenkSwardt** [comment]
Issue logged on Jira - https://particl.atlassian.net/browse/PBD-441

**Comment by zaSmilingIdiot** [comment]
In future, when reporting issues, could you perhaps provide the following:

- A description of the actual problem. For example, I understand from your logged issue that the conversion is not converting all of your available and spendable public PART to anon. Is this the issue?
- A set of instructions on how to reproduce the problem. So that we can can attempt to reproduce the problem and investigate.
- An indication of what the expected outcome is meant to be. In other words, something along the lines of: "after following the steps, x happens but its expected that y occurs".
- Any additional information that might assist or be applicable, such as whether the core is fully synced, etc. Screenshots, for example, help here as well.

This helps us to investigate any specific problem. For example, a broad sweeping statement of "conversion doesn't seem to be working for me" doesn't help us understand where its not working. Generally conversion does work, so if there is a problem occurring in a specific scenario or under a set of particular circumstances, then we need to know what those conditions/circumstances are.

**Comment by zaSmilingIdiot** [comment]
The reason I mention the above is that your steps to produce what you claim is the issue does not appear to be accurate.

The flag that you clicked on has the help text "Show reported listings only"
The Help text that forms part of the page header, which provides a general summary of the page, displays the text "Here you will find all publicly available Listings for sale. ..."

This doesn't describe what you are then looking to change?

**Comment by zaSmilingIdiot** [comment]
We've updated the flag icon hover text to indicate what clicking it would be changing, rather than having the static .'Show reported listings only' text present.
This was made available in the v2.0.0 mainnet release already.
