### ISSUE TITLE
anon convert

### ISSUE THREAD

**Issue by chunkingcheese** [particl/particl-desktop#1629]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..
2. ..

# More information

- Operating system and version:
- Client version:

**Comment by chunkingcheese** [comment]
I  am using the market place to convert coins to anon and when I tell it to convert all, it is only converting about 32 coins even though it says I have 40 in my public balance.  Am I misunderstanding what should be going on here?  It says I have 40 spendable and 32 in my locked and pending.

**Comment by chunkingcheese** [comment]
I am running windows 10.

**Comment by zaSmilingIdiot** [comment]
Hi @chunkingcheese Could you perhaps provide the following:
- a description of the actual problem. For example, I understand from your logged issue that the conversion is not converting all of your available and spendable public PART to anon. Is this the issue?
- A set of instructions on how to reproduce the problem. So that we can can attempt to reproduce the problem and investigate.
- An indication of what the expected outcome is meant to be. In other words, something along the lines of: "after following the steps, x happens but its expected that y occurs". 
- Any additional information that might assist or be applicable, such as whether the core is fully synced, etc. Screenshots, for example, help here as well.

This helps us to investigate any specific problem. For example, a broad sweeping statement of  "conversion doesn't seem to be working for me" doesn't help us understand where its not working. Generally conversion does work, so if there is a problem occurring in a specific scenario or under a set of particular circumstances, then we need to know what those conditions/circumstances are.

**Comment by zaSmilingIdiot** [comment]
Any feedback on this issue for us?

**Comment by zaSmilingIdiot** [comment]
Closing due to lack of feedback
