### ISSUE TITLE
Need to restart particl desktop in order to see a "1" at the buy section even though status is already "payment" and it's buyers turn

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1640]
The indication that it's the buyers turn in the process of bidding/paying/escrow seems to not show up as a "1" after "buy" in menu whenever client is open and seller took action. The status of the listing is "payment" however. upon restarting client, the "1" indication is there. Not sure but i think reloading the wallet or switching from a regular to market wallet may fix it as well. There is however a bug here it seems that the data is not refreshed when action is taken by seller and buyers client is open at same time..

- Operating system and version: Win10x64
- Client version: Latest testnet before mainnet

**Comment by PARTimprovert** [comment]
note: my wallet's never been locked!

**Comment by zaSmilingIdiot** [comment]
Thanks for mentioning this. The functionality has been fixed and the change is currently available in the alpha3 build for testnet, and will be included in the upcoming v2.0.0 mainnet release.

**Comment by cryptoguard** [comment]
@PARTimprovert 

We've identified this bug as a minor bug and it qualifies for bounty payment. Please write in this comment section a private address of yours so that we can forward your bounty payment. 

Thanks for participating in the bug bounty and helping us identifying issues! It is really appreciated!
