### ISSUE TITLE
Rename transaction when bidding for listings

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1646]
When making a bid, a transaction is initiated named: converted --> blind
This is somehow misleading, since it's an identical naming when you are manually convert e.g. public to private coins.

Since with bidding it's an automatically initiated transaction to convert anon coins into blind coins (I guess), I would rather give this transaction a different name, for example,  anon --> blind

The steps needed to recreate the bug/issue:
1. Make a bid on a listing
2. Convert manually public coins
3. You see that same name for both transactions, but they "behave" totally different in terms of their consequences on the overall balances --> is confusing for the most users

(Making a bid on a listing will make use of anon utxo which might result in certain coins ending up in a pending status contrarily to the manual convert)

**Comment by zaSmilingIdiot** [comment]
> When making a bid, a transaction is initiated named: converted --> blind
This is somehow misleading, since it's an identical naming when you are manually convert e.g. public to private coins.

This is exactly what happened from the perspective of the wallet. There was a transaction that converted funds from anon to blind. Hence the 'Converted -> Blind' label is still correct.

The proposed label 'anon -> blind' says pretty much the exact same thing. The thing is, whether the step occurs automatically or manually, the point is that the record states that a particular type of transaction occurred. Automatic or manual transactions all use the same core rpc request, so from the perspective of the core (and thus your wallet transaction history), the request for the transaction is the same. In other words, there's no store of the source of the transaction.

**Comment by kangoala** [comment]
Ok, that's reasonable.
However, for me it's somehow confusing when trying to understand what the marketplace does with my particl balances. There might appear suddenly several identical named transactions which might change the balances in a non comprehensible way. Particularly the UTXO stuff with an undefined number of coins going into a pending or locked status is annoying and might look like there's something going wrong.

**Comment by kangoala** [comment]
Hi abansemer,
there's another inconsistency which migth lead to irritation.
After making a bid and locking my payment into escrow, I do get a transaction when seller ships it's item. This transaction is anonymous and it's called "received". However, I do not receive any coins, instead blind balance and total balance get reduced by the selling price. 
Probably from core perspective again this might be correct but for the user this might cause some questions about the reliability of the marketplace. 
Couldn't you rename easily those transactions?
