### ISSUE TITLE
Receiving 0 PART sent from my Default wallet to my Market wallet

### ISSUE THREAD

**Issue by jeremyfritzen** [particl/particl-desktop#1652]
# Describe bug/issue

I sent 1 PART from my default Wallet (ANON private address) to my Market wallet (ANON private address) but the Net amount received is 0 PART.
I can see the transactions have been well executed as they are displayed on each wallet.

# How to reproduce

1. Go to default Wallet (which contains coins on Public and on Anon)
2. Send a payment from Anon to the private address related to the Market wallet (in Anon)
The transaction is displayed as follow in the Default wallet
![image](https://user-images.githubusercontent.com/26802442/63211195-43967d80-c0f4-11e9-93f9-6488f047c255.png)
3. Then, in the Market wallet, I see the transaction but the amount received in 0 :/
![image](https://user-images.githubusercontent.com/26802442/63211212-93754480-c0f4-11e9-97bc-393618480270.png)

Do not know why this happened?
Was the amount to little?

Thanks for your help and congrats to the team!

# More information

- Operating system and version: Windows 10
- Client version: 2.0.1 (beta)

**Comment by zaSmilingIdiot** [comment]
Anon payments received require that the wallet be unlocked at least once in order to detect the amount that the transaction was for. The 'crossed out eye' icon, to the right of the 'RECEIVED' word in the 2nd screenshot above, should indicate this: hover of the icon and it should explain the need to unlock the wallet at once since receiving the funds.

Note that you may need to navigate away from the page and then back to it to update the display to actually show the value.
