### ISSUE TITLE
Cold version of desktop will not load past splashscreen

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1658]
When Particl Desktop is loaded on a cold machine (a machine without an internet connection) the splash-screen is displayed indefinitely. Tested on Mac OS X and Windows machines.

Perhaps this is not a bug, but at the least a message or some form of feedback should be shown?

A work around is to load it onto the computer when the machine is online and then take the computer offline, it then loads fine each time there after.

**Comment by zaSmilingIdiot** [comment]
Particl Desktop requires a valid particl-core application to be available for it to run. This is either in the form of a previously downloaded (and verified) particl-core, or, an existing particl-core needs to have been started prior to Particl Desktop starting and then starting PD with some optional parameters to tell it how to connect to the already running core instance.

Its very possible that we provide the option for a 'lite' client experience in the future (or at least the option to run in 'lite' mode until the blockchain has downloaded). But incidently, this wont start do anything either if no internet connection is present. Might be a slightly better "experience" though, as the PD will launch and present the main application window, rather than hanging/stalling in the loading/launching screen.

Something that can be kept in mind for future changes...

**Comment by zaSmilingIdiot** [comment]
Should be resolved as of v3.3.0

Particl Desktop now displays the splash screen, does some initial loading, and only once at the "main menu" it will attempt to download/start/connect to a particl-core node. The particl-core node startup is also configurable now, for interest.
Regardless, this now means that the application launches correctly without first requiring that a connection to a particl-core node is established.
