### ISSUE TITLE
Dissable cold staking popup dialogue does not dissapear

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1660]
When the 'disable cold staking dialogue pops' up (when you select it from the cold staking section on the right of the wallet overview screen) if you click the red button marked 'Disable Staking' the dialogue persists until you press the cancel button to close the box. Cold staking is cancelled however because the action of cancelling cold staking still seems to be carried out. Seems to happen and all versions of the client.

**Comment by zaSmilingIdiot** [comment]
Can you perhaps confirm whether the wallet started in a state of being 'unlocked for staking only'?

I suspect this to be the case. If so, this would not be the only modal that has this issue. And that are exactly 2 (cold staking or whichever) modals displayed over each other, which is why it appears that actioning and then cancelling works. The double modal can be tested by:
- starting with a wallet with an encryption status of being  "Unlocked - staking only"; 
- select the cold staking (or other) modal;
- provide a correct password when prompted;
- when the cold staking (or other) modal appears, click the cancel button on it - this should appear as doing nothing, but click the cancel button again and the modal should close.

If this is the case, its a side effect of initial processing the desktop does in attempting to return the wallet to the initial encryption status of being 'Unlocked - Staking only' after the 'Unlocked' timeout completes. This results in a second modal being incorrectly immediately displayed.

A fix has been created, and will make its way into a future release version.

**Comment by zaSmilingIdiot** [comment]
The multiple modal/dialog window issue resulting from the wallet starting in an "Unlocked for Staking" state, as mentioned above, has been resolved as of v2.2.0. This should resolve the stated problem.

Would it be possible to try with the new version and provide feedback on whether the issue has been resolved?

**Comment by zaSmilingIdiot** [comment]
Now in v2.3.0, so closing this for now: can be re-opened if the problem persists.
