### ISSUE TITLE
Seller can give feedback to buyer when cancelling an order

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1682]
When I get as buyer my order cancelled, it would be nice to get an feedback from the seller why this happened (E.g. out of stock, not deliverable to your country, ...).
Give the seller the opportunity to send a short message or to select one out of a set of preconfigured replies.

**Comment by zaSmilingIdiot** [comment]
This functionality already exists as a part of the Bid Reject action: when a bid is received, then the bid can be rejected by the seller with a predefined message.

Granted, we can likely add a number of additional predefined messages, but it would be helpful to get feedback on types of messages wanted/needed.

Typically, once a bid has been accepted, both parties have expressed interest in transacting. Either party may then cancel the process until the escrow transaction has been created: typically a Cancellation action should occur when something happens and either party wants to indicate that they wish to back out from the transaction. Perhaps something went wrong and one of the parties no longer has the funds available, or one party feels the other is not responding quick enough. And so they want to abort the process.

If the seller, on receiving a bid, does not wish to accept the bid, then they should reject the bid. And are thus able to provide an indication as to why they rejected it.
I would guess that there is the case where a seller accepts more bids than what they have stock for, for example, due to possible buyer cancellations during the process. But this seems to be related to sellers managing their stock levels, in which case stock level management is perhaps a slightly different problem to solve.

**Comment by zaSmilingIdiot** [comment]
A solution exists now in the v3 Particl Desktop application (as of about Particl Desktop v3.1 or v3.2) where the buyer and seller can send direct messages to each other relating to an order. Even after an order is cancelled, if so desired, thus it should now be possible to communicate with the other party to attempt to determine why a particular order was cancelled.
