### ISSUE TITLE
Particl locked in escrow and user backed out of purchase after accepting bid.

### ISSUE THREAD

**Issue by scoobasteve83** [particl/particl-desktop#1695]
**Describe the bug**
I was selling an item on the marketplace. 
A user placed a bid.
I accepted the bid and my funds went to escrow.
The user never followed through with the purchase.
The bid was cancelled. 
My funds are still locked somehow.

**To Reproduce**
Sell an item have the buyer place a bid then accept the bid placing your funds in escrow. Then tell the user not to follow through with the purchase. Funds will be locked this is a sure bug as funds should automatically release in this case.

**Expected behavior**
The funds should have been released after bid was canceled and no purchase was made there should have been a couple day timeout on purchase then have the funds released.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. OSX 10.1.4.5 or Windows 10 or Linux Ubuntu 18.10]
 - Particl Desktop: [e.g. v2.2.0]
 - Particl Core: [e.g. v0.18.1.6]

Particl Desktop 2.3.2
**Additional context**

This happened on an earlier version I am trying to sync to the new version as we speak but am having issues connecting to peers. Was hoping the latest version would provide some relief as this has been an ongoing issue I've tried to get help for.

**Comment by zaSmilingIdiot** [comment]
Just to note: by accepting the bid, the funds would not have been "locked" in escrow., but reserved for escrow. The reserved funds are still in your wallet and in your control (and there is a way to move them from 'reserved' to spendable again, although its a manual method).

Normally, reserved funds would have been released back to being spendable again when the bid/order cancellation message from the buyer was received, or you cancelled the order yourself. There isn't sufficient indication here what the steps taken were (if you cancelled,, then possible marketplace error, otherwise if the buyer cancelled then possible cancellation smsg not received or perhaps a marketplace error), and its now too late to try and obtain log information from the event to track down exactly what was happening in the marketplace service on your side.

I'm going to close this for now due to age and inability to track down the exact cause of the issue. Also, with the imminent release of v3.0, both the desktop and marketplace have undergone substantial changes and this type of issue is more than likely no longer present (and to also add, smsg deliver is a lot better now than what it was at the time this issue was created). If something simlar occurs again using the new version, then a new issue can be created or this issue can be re-opened.

**Comment by scoobasteve83** [comment]
Well bummer is I purchased part at a fairly high rate of sale so to speak and now its impossible to buy PART if you live in the United States wish there were an easy way to do It I'd spend a grand today if there were.
