### ISSUE TITLE
Mandatory windows 10 update causes client to not start correclty.

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1702]
Mandatory windows 10 update and restart seem to cause Particl Desktop to shutdown unexpected and then be unable to restart.

I went to bed about 10pm, Particl Desktop was ruing when I left. Windows had be threatening a 'scheduled' restart at some point. But when I got up this morning the computer had restarted (I assume as much as all my running apps had closed) and the scheduled restart icon in the sys tray was gone. I assume it was a scheduled restart last night. I could not rule out other scenarios like windows through an error and restarted unintentionally, and as it was restarting then did the OS updates too.

The current work around suggested when I discussed this with zaSmilingIdiot is to delete the .cookie file typically located at: C:\Users\[Username]\AppData\Roaming\particl\.cookie. Once deleted Particl Desktop to restart successfully.

I am using  v2.2.0 of Particl Desktop

**Comment by zaSmilingIdiot** [comment]
Seems the Windows update force stopped particl-core without providing it sufficient time to properly shutdown. Doing this to any process can lead to issues, which is why its not recommended to force kill services and processes.

Regardless, the cookie file is used to generate randomized auth details for connecting to core's rpc service, and would typically be created at core's start and then removed when core shuts down. 
In earlier versions of particl desktop, there was a problem in which PD would start core, and then poll for the existence of the cookie file to know that core had started (so that PD could connect to core's rpc service). However, there may be a number of seconds between the start of core and core generating the rpc service cookie file. In cases wherecore didn't shut down properly and clean this cookie file up, PD would almost immediately after starting core find the cookie file and extract the auth details from it. Except these were the incorrect details, because once the core rpc service was actually started, it would have regenerated the rpc auth details in the cookie file (ie: the cookie file would have been updated and the auth details originally in it would no longer be valid). And this leads to problems and issues such as this one.

In v2.3, additional checks were added so as to attempt to recheck the cookie file if auth details failed. Which prevented this type of issue from happening.
