### ISSUE TITLE
MP list view: Automatically display new items | Abandon "refresh" button

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1714]
**Is your feature request related to a problem? Please describe.**

A user needs to hit the refresh button to display new arrived listings. This UX can be optimized.

**Describe the solution you'd like**

If new listings arrive in the DB they should be instantly displayed at the top of my list view without interfering my actual scroll position. 

When new listings arrive in my (filtered) listings, at the top of my scroll-view area an indicator shall be visible "x new items arrived: Jump to 'new arrivals'?" ... once 'new arrivals' button is hit, it brings me up to the first item that was newly loaded and my further scrolling would go up to see more of the new arrivals. If more than 1 row is scrolled up manually, the notification pane disappears, alternatively by hitting a 'dismiss' button.

![pd_listing_ux](https://user-images.githubusercontent.com/25568865/82887147-e1528f00-9f47-11ea-961f-d7cffd4129bd.jpg)
An additional semi-transparent button shall be shown in the bottom right corner indicating a 'jump to start' function. This brings the user to the top of the list where he/she started scrolling down. Once clicked it changes its color indicating 'jump to top' and a hit would bring the user to the most recent loaded and displayed item, which defines the top of the whole list.

The "refresh" button becomes obsolete. 

The UX becomes more natural.

**Describe alternatives you've considered**
It is an UX improvement. No alternative here.

**Additional context**
It may be necessary do have an additional listing controller that takes care of not having too much listings in the memory at the same time.

**Comment by zaSmilingIdiot** [comment]
Is this not the same functionality as the refresh button, but just moving the refresh button to a different position and calling it something else?

The current refresh button, when clicking it, performs the "jump to the top" action and includes the newer listings. Which appears to be the same as what is being proposed...?

**Comment by DrDBanner** [comment]
Partially. 

Here the user is instantaneous able to scroll up to see new listings without additional interaction.

The bottom right arrow implementation is an enhancement of the current behaviour. One click brings me back to the top of my list, where I started scrolling, a second click brings me to the top of the complete list, where the most recent item is shown. This is partially redundant to the notification bar and is intentional. 

The current implementation does not respect the current scroll position. If the refresh button is hit it refreshes to the first page of the paginated items and user loses the position where he/she has been.

**Comment by zaSmilingIdiot** [comment]
So if I understand this correctly, this is an attempt at a desktop variant of the mobile "pull-to-refresh" action?

What I'm not liking here is:

Firstly, the top bar suggestion effectively replaces the existing refresh button indicator. Its purpose is to indicate new listings have arrived (since the start of viewing the page) but are not rendered in the current list displayed, which is exactly the same as the refresh button and its indicator. So while potentially getting in the way of the user's actual activity (of browsing listings), and then requiring the user to explicitly dismiss it if not wanting to take its action, the end goal is exactly the same as the current refresh button (and its indicator).

In other words, there does not appear to be any actual benefit to including the top bar, except perhaps to provide for a different refresh button indicator. And a dismissable bar notification stuck to the top of the viewport does not work well here, if that is the case.

Secondly, on the floating action button (FAB) down the side of the page: by hiding the actual refresh action behind a second action, this now requires the user to click twice to load new listings: first to scroll to the top of the page, then a second time to actually refresh the listings displayed. Apart from hidden actions which typically results in user frustration, this actually has 2 other immediate negatives: 
- firstly, when the user has already scrolled down at least some of the way, there's no means to indicate that new listings are available. Notifications should be in relative close proximity to where the action is actually going to happen (prevent users searching for how to take actual action on the current notification), so using the top bar for notifying the user while still having the second action on this side FAB is somewhat pointless (and removing the 2nd action from the FAB means that its a scroll-to-top button, which hardly justifies having this in a desktop application). If instead, an indication of new available listings is added to the FAB , then this is exactly the current refresh button activity, but now instead of doing the action the user intends, said user needs to click the FAB twice to actually perform this action. Which seems more akin to buggy behaviour than anything else.

- second, this doesn't seem to provide any actual benefit over the current refresh button. The user still needs to click a button (twice now instead of once) if they are part way scrolled down the page, to display newly arrived listings. And if the user is already at the top of the page, the button acts exactly the same as the current refresh button (user still needs to click it to display newly arrived listings). So this appears to be introducing complexity to perform basically the same action as before.

If the request is to change the refresh button position, look and feel, and/or its indicator, then lets rather discuss that. For example: moving the refresh button to be a FAB, but only having its single purpose... no multiple click actions.
But I don't think its feasible to consider the removing of the refresh button and instead introducing (multiple) other controls (at an increased complexity) to effectively achieve the same result.

**Comment by DrDBanner** [comment]
> Firstly, the top bar suggestion effectively replaces the existing refresh button indicator. 

Correct. Users just don't find/see it immediately. 

> Its purpose is to indicate new listings have arrived (since the start of viewing the page) but are not rendered in the current list displayed, which is exactly the same as the refresh button and its indicator. 

Only the indication portion. But much more prominent. **Interaction design** needs to be at the lowest user level, that even the cognitive 'weakest likely user' even gets it.  

> So while potentially getting in the way of the user's actual activity (of browsing listings), and then requiring the user to explicitly dismiss it if not wanting to take its action, the end goal is exactly the same as the current refresh button (and its indicator).

Not exactly. The user dismisses it while scrolling upwards 1 row, if no other action is taken. The end goal is not the notification portion. The end goal is to have a seamless scroll experience without the need of hitting the 'refresh' button.

> Secondly, on the floating action button (FAB) down the side of the page: by hiding the actual refresh action behind a second action, this now requires the user to click twice to load new listings: first to scroll to the top of the page, then a second time to actually refresh the listings displayed. Apart from hidden actions which typically results in user frustration, this actually has 2 other immediate negatives:

It is not hiding anything. It is a semi-transparent helping tool to accelerate navigation within a big list of items *at some point of time. New items have already been loaded and displayed. But that is not the point of usability improvement here. The interaction design here is to bring the user back to the place where he startet scrolling with a single click at the point of action (which is not possible at the moment; more frustrating is that if I press refresh I have no indication which items are new and the user does not understand why items are not there anymore -> new FR), but meanwhile new items have been loaded and displayed a second interaction is needed to bring the user to the very top of the list including the new listed items. Which is a natural thing. The problem with the actual solution is that a user needs to press

> firstly, when the user has already scrolled down at least some of the way, there's no means to indicate that new listings are available. Notifications should be in relative close proximity to where the action is actually going to happen (prevent users searching for how to take actual action on the current notification), so using the top bar for notifying the user while still having the second action on this side FAB is somewhat pointless (and removing the 2nd action from the FAB means that its a scroll-to-top button, which hardly justifies having this in a desktop application). 

You think rational, and that is very good. That is unfortunately not what interaction design is about. It is about making things easy for users. Please see the redundancy here as an advantage for usability. Especially in the light of two different locations where a user is actually able to do the same thing. We have users that use trackpads and users that do use the mouse as pointing device. Both have different needs and this must be taking into consideration. So different proximity hotspots. 

> If instead, an indication of new available listings is added to the FAB , then this is exactly the current refresh button activity, but now instead of doing the action the user intends, said user needs to click the FAB twice to actually perform this action. Which seems more akin to buggy behaviour than anything else.

You are moving to an IF situation which was and is not proposed. You are correct. That behaviour is buggy if you would do it this way -with the indications within the FAB.

> second, this doesn't seem to provide any actual benefit over the current refresh button. The user still needs to click a button (twice now instead of once) if they are part way scrolled down the page, to display newly arrived listings. And if the user is already at the top of the page, the button acts exactly the same as the current refresh button (user still needs to click it to display newly arrived listings). So this appears to be introducing complexity to perform basically the same action as before.

**This is not the case. A user will be able to scroll seamless to new arrivals.** But has additional helpers that make life easier if the seamless scrolling feature is implemented. It is just thinking outside the box and being ahead of the curve.

The actual behaviour forces the user to hit the refresh button and loose track. 

> If the request is to change the refresh button position, look and feel, and/or its indicator, then lets rather discuss that.

This is not the subject of the discussion.

I hope that I have been able to expand your imagination a bit, so that you might recognize the improved user experience.

**Comment by zaSmilingIdiot** [comment]
Not going to happen in the upcoming releases, so closing this.

**Comment by garbagiountilitisnt** [comment]
This is a very significant issue in my opinion and should get some priority. The refresh button for new listings is not going to cut it, although i understand why its implemented this way for now. New listings will have to pop-up automatically, as DrDbanner pointed out. Basic user experience, a refreshing button here is a terrible solution
