### ISSUE TITLE
"Export private key" button

### ISSUE THREAD

**Issue by Yewho** [particl/particl-desktop#1719]
**Is your feature request related to a problem? Please describe.**
to get my private key i need to use the console (not userfriendly)

**Describe the solution you'd like**
Add a menu item with the option  "Export Private Key"
protected with the passphrase

**Describe alternatives you've considered**

**Additional context**
![privatek](https://user-images.githubusercontent.com/54146210/86899835-ceb4a380-c10a-11ea-89b8-daff7a56e5c0.png)

**Comment by DrDBanner** [comment]
I am strong against this. Because a seed is a VERY powerful tool which would get exposed with a single screenshot. Outcome: you lost all of your coins INSTANT in any pub/priv pair protected under that seed.

After the main issue has been changed: having Easy single key extraction seems reasonable. Though obfuscation of the pubkey in this process may be beneficial.

**Comment by Yewho** [comment]
most of the wallets have this option
