### ISSUE TITLE
Error: The wallet passphrase entered was incorrect

### ISSUE THREAD

**Issue by executionByFork** [particl/particl-desktop#1728]
**Describe the bug**
I am trying to create my first wallet on particl desktop 2.3.5 Windows exe version. I am able to generate the recovery phrase and get past the screen verifying that I have saved the phrase. However, something is going wrong with the password fields. When I get through both the recovery password creation and the encryption password creation, I get an error stating "The wallet passphrase entered was incorrect" as if I am trying to unlock a wallet. I am creating one.

It does not matter whether I leave the recovery password blank or fill one in. It doesn't matter if I use the same password on both the encryption and recovery passwords or two different ones, the outcome is always the same. I've tried multiple times (with multiple passwords) and double checked each time that both the password and confirmation on both forms match each other. I still get the error. I cannot create a wallet.

**Expected behavior**
I should be able to create a wallet.

**To Reproduce**
1. Click "Create New Wallet"
![image](https://user-images.githubusercontent.com/20407804/92855035-71adc600-f3b7-11ea-85e7-76eb401964c3.png)

2. Copy the recovery phrase and fill it in on the confirmation page

3. Create a recovery password (or don't, this step changes nothing)
![image](https://user-images.githubusercontent.com/20407804/92855566-09131900-f3b8-11ea-86b9-9c23aeb9178a.png)

4. Create an encryption password
![image](https://user-images.githubusercontent.com/20407804/92855638-1f20d980-f3b8-11ea-95bf-e357494549b3.png)

5. View error
![image](https://user-images.githubusercontent.com/20407804/92855710-33fd6d00-f3b8-11ea-9038-9c29dc98745f.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - Particl Desktop: 2.3.5
 - Particl Core: idk, I chose Windows exe from the downloads page here: https://particl.io/downloads/

**Comment by executionByFork** [comment]
I am still having this issue upon returning to look at particl again, and still cannot create a wallet. Upon investigating further I came across the following error in the dev console. It looks like a backend server running on localhost is not starting properly, or is not accessible.

Am I supposed to have a separate piece of software installed besides Particl Desktop on my computer? Do I need particl-core? The documentation makes it seem like all I need to do is download the latest version and create a wallet. If this is not the case and I am supposed to install particl-core, the documentation needs to be updated to reflect this.

![image](https://user-images.githubusercontent.com/20407804/110551199-b8784080-80fa-11eb-81f8-d846d7bfd203.png)

**Comment by executionByFork** [comment]
I have ensured that the windows firewall allows all particl apps to communicate on both private and public networks, just to make sure that this isn't a firewall issue, and the error still occurs. On app load there are several errors that occur before I interact with anything
![image](https://user-images.githubusercontent.com/20407804/110556127-84ede400-8103-11eb-8958-0e8825285e01.png)

I am attaching the [debug.log](https://github.com/particl/particl-desktop/files/6112192/debug.log). As well as a smaller [log file](https://github.com/particl/particl-desktop/files/6112183/tmpLog.txt) from just one run of Particl Desktop, where I attempted to create a wallet as described above. The logs folder at `C:\Users\<username>\AppData\Roaming\Particl Desktop\logs` is empty.



I was successfully able to create a wallet using `particl-qt` aka `%appdata%\Particl Desktop\particld\unpacked\particl-0.19.2.5\bin\particl-qt.exe` such that it shows in the upper right drop down. Also `particl-cli` shows the new wallet.
```
.\particl-cli.exe listwalletdir
{
  "wallets": [
    {
      "name": "TEST"
    },
    {
      "name": ""
    }
  ]
}
```

However opening Particl Desktop still drops me in the create wallet page, and creating on Particl Desktop errors in the same way.

**Comment by zaSmilingIdiot** [comment]
I seem to have missed this issue being raised.

For reference, the "The wallet passphrase entered was incorrect" is referring to the Encryption Password value, **not** the Recovery Password value. 
The Encrypted Password value is very simply: the password used to encrypt various details in the wallet. This provides a sort of physical protection to the wallet file itself: if an attacker got access to the physical wallet file on your machine (either directly or via a backup copy for example), then having various details encrypted inside the wallet file means that the attacker would not be able to spend funds from the wallet as if they owned it.
The Recovery Password provides an extra (25th), user provided, word for the mnemonic. If someone randomly tried various mnemonic words and happened to obtain the correct sequence of words that matches the 24 words generated for your wallet, the I seem to have missed this issue being raised.

For reference, the "The wallet passphrase entered was incorrect" is referring to the Encryption Password value, **not** the Recovery Password value. 
The Encrypted Password value is very simply: the password used to encrypt various details in the wallet. This provides a sort of physical protection to the wallet file itself: if an attacker got access to the physical wallet file on your machine (either directly or via a backup copy for example), then having various details encrypted inside the wallet file means that the attacker would not be able to spend funds from the wallet as if they owned it.
The Recovery Password provides an extra (25th), user provided, word for the mnemonic. This helps to avoid recovery of the wallet by randomly enumerating the mnemonic words.

During wallet creation, if providing an encryption password, then the actual wallet file created is set up to be encrypted. This is important for the next steps. Which is why the prompt to unlock the wallet occurs towards the end of the create wallet process.

Some additional notes:
> Am I supposed to have a separate piece of software installed besides Particl Desktop on my computer?

No, not necessary... Particl Desktop will resolve any additional software needed to start up.

> Do I need particl-core?

Yes, but you do not need to download particl-core separately. Particl Desktop, on starting, will check to determine if particl-core is available, and "install" it (and start it) if necessary. The creation of the wallet process relies on core running already, so you wouldn't have gotten to entering the create wallet process if core was not already installed and running.

> However opening Particl Desktop still drops me in the create wallet page, and creating on Particl Desktop errors in the same way.

This is because while you have 2 wallets (with likely only the 'TEST' wallet initialized), the default (not-named) wallet is yet to be properly initialized. In the v2.x releases of Particl Desktop, there's almost a hard requirement that the default wallet is initialized correctly: a check is done just after startup and the application defaults to presenting the create/restore wallet process for the default wallet.
In v3, this works slightly differently: the create/restore wallet process is presented for any wallet not yet properly initialized, but its possible that if you have another wallet that is initialized correctly already then you can switch to using that wallet without completing the wallet setup process. This would allow, in this case, for the TEST wallet to be changed to and used instead of the uninitialized default wallet. The exception here is that if only the default wallet exists and its not initialized correctly, then well, there's no alternative wallet to switch to, so you need to complete the setup process for the default wallet. (But its always possible to have an alternative wallet because the market module creates a wallet for you as well).

---


As for what the actual error is, I don't see anything problematic standing out in the log files provided. Only if this default wallet is still not working and its not being used, it should be possible to resolve the situation by trying to recreate the wallet by doing the following:
- Ensure that any particl-core, Particl Desktop, and/or Particl QT applications that are currently running are stopped (wait for them to properly stop and shutdown if any are running).
- Backup the file `C:\Users\Arnold\AppData\Roaming\Particl\wallet.dat` to somewhere in case something goes wrong.
- Now remove the file `C:\Users\Arnold\AppData\Roaming\Particl\wallet.dat`
- Start Particl Desktop again, and complete the wallet setup.

When particl-core restarts, if the default wallet (the 'wallet.dat' file) is not present it gets recreated. Which should then allow for a restart of the wallet creation process for the default wallet.

**Comment by zaSmilingIdiot** [comment]
Is this issue still occurring on the latest version, v3.0.0  ?

**Comment by zaSmilingIdiot** [comment]
Closing - no response. The recommendation is to use the latest release version, as v3 was a significant re-write of the v2 codebase (the version used in the reported issue) and is thus resolved in the latest version.
