### ISSUE TITLE
Retracted issue

### ISSUE THREAD

**Issue by cleansanchez** [particl/particl-desktop#1734]
If the save shipping profile is checked, cannot proceed with the order.

![01](https://user-images.githubusercontent.com/44262926/103144930-8d03cd80-4729-11eb-855d-b871a6a70989.JPG)

![02](https://user-images.githubusercontent.com/44262926/103144936-9f7e0700-4729-11eb-8520-29c4b87f5090.JPG)

**Versions (please complete the following information):**
 - OS: Windows 10 home
 - Particl Desktop:V3 testnet
 - Particl Core: 0.19.11

**Comment by zaSmilingIdiot** [comment]
Just noting that you should be able to close an issue if you logged it and feel that it is no longer relevant.

For others asking thr same question, the reason that the proceed button is not active is because a shipping profile requires a non-empty name/label in order to be saved, which was not filled in (its the field just to the right of the checkbox).
