### ISSUE TITLE
V3 - Marketname and marketdescription exceeds maximum characters

### ISSUE THREAD

**Issue by Sv3n1988** [particl/particl-desktop#1735]
**Describe the bug**
It's possible to exceed the maximum charaters in the fields marketname (50) and marketdescription (150) when creating a market. There is a counter but the input should stop when i reach the maximum input. Also in the marketpreview you see the additional characters.

**To Reproduce**
1. Go to 'Create new market'
2. Fill in the marketname and marketdescription and exceed max characters

**Expected behavior**
The input should stop when you reach the maximum characters

**Versions (please complete the following information):**
 - 3.0.0-RC-test002

**Comment by zaSmilingIdiot** [comment]
Its possible that the user makes a mistake in the input, decides the complete the input and then goes back to fix the error. More so, the problem applies to copy/pasting external text: if the pasted text is too long then it needs to be truncated at the maximum limit. But its also possible that the intention of the user was to keep the last segment of text and remove something from the middle, or the start of the copied text if its too long.
Thus, the input fields allow for longer inputs to be provided, and leave it as an exercise to the user to shorten it as they deem fit rather than making assumptions about where/what to remove.
Also, this way, the user can see by how many characters their input exceeds the maximum limit, and make changes as they deem necessary (which, for example, may lead to them deciding to change the input text completely).

**Comment by Sv3n1988** [comment]
I partially agree with you. However, I would like to make two comments. 1) In other parts of the solution, the words in a field ARE truncated (for example when sending a payment, the field 'narration' (1/24)) when reaching the maximum limit. So the operation of this is not consistent in the solution. 2) if you have a market created with too many characters, there will be no security warning if you click on the button 'confirm and create market'. The text (for longer texts) is also out of the picture once the market has been created. So I think there should be at least a security warning before you can create the market definitively.

**Comment by zaSmilingIdiot** [comment]
Yeah, I think I read your initial issue a little too quickly. I was just reviewing it, and realized that what you were referring to was in fact a bug, and you were correct for reporting it. My apologies for assuming that your issue was attempting to report something else.

As per your original reported issue, this is a bug, and I have updated the labels on this issue to reflect as such. The error has actually also been addressed previously, so will make it out in the next release. I'm going to leave this issue as closed though due to it having been fixed.

My apologies again for jumping to a conclusion.
