### ISSUE TITLE
V3 - Renaming Process Flow for buyer and seller

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1742]
Currently the Process Flow is described as follows:
Bidding --> Accepted --> Escrow --> Packaging --> Shipping --> Completed

Proposed Process Flow:
For the buyer it's not of too much importance to know about the packaging status. For the seller one could add the packaging status in brackets as well.
Bidding --> Accepted --> Escrow Request --> Escrow locked (Packaging) --> Shipping --> Completed

**Comment by zaSmilingIdiot** [comment]
We've had this type of request before, and on one hand we have requests to "make it more intuitive" by removing the apparent double mention of escrow, as well as the opposite request  to rather display it.

The current flow 'labels' seem to nicely compromise on these, wherein the "Escrow" step is actually "Request Escrow" and the "Packaging" step afterwards implies that the escrow was completed since the process moved onto the next step. 
Additionally, the current steps provide hints for actions required by the sellers: with the v2 marketplace buyflow step labels using the "escrow" and "escrow complete" labels it was often the case that the seller would ship the item prior to actually completing the escrow. The current flow hints to the seller that after the escrow request from the buyer is received an action from them is still required in order to move to the packaging step. The idea here being that for newer users of the system, it makes a bit more sense that having to first figure out what the different steps mean. The more experienced user will no doubt understand that the move from escrow request to packaging implies that the escrow is complete, and that knowledge doesn't necessitate a verbose label indicating as much. Whereas with the less experienced users, the labels tend to help guide them through the process, and is thus more helpful to them.

Unless there is significant support for a change in buyflow step labels for the "packaging" step, I think it best to leave these in its current form.
