### ISSUE TITLE
V3 - Menu item names are inconsistent

### ISSUE THREAD

**Issue by Sv3n1988** [particl/particl-desktop#1752]
A small point of improvement would be to change the menu item names so that they are consistent with terms used in other menu items and in other parts of the program. In the section 'market' we see on the left side the menu with the items: '**purchases**' and '**sell**'. The words '**Purchases**' and '**sell**' are inconsistent. It would be better to call them '**purchases**' and '**sales**' or '**sell**' and '**buy**' or '**buy orders**' and '**sell orders**'. The latter (buy orders & sell orders) would be the best in my opinion because it also corresponds to the terminology used in the 'overview' section. These terms are also used as a title when you click on the menu item itself. Moreover, a buy order does not necessarily have to be a definitive purchase (buy order can also be canceled).

**Comment by zaSmilingIdiot** [comment]
We've actually been through a couple iterations of changing these types of labels. 
- using "buy" and "sell" was found to be confusing, but mostly because "buy" implies the action "buy" and there was confusion about where to find the listings in that particular section, ie: the particular section is for handling items after they have been 'purchased'/'requested', rather than representing the place where items can be purchased from. Further, since the cart is also a menu item, it can also be viewed as redundant because 'buy' and 'cart' could represent the same activity. Basically, the word 'buy' has multiple different uses and intents which depend on context that can't be derived only from the menu itself. Seems that "sell" was generally relevant though.
- "buy orders" and "sell orders" is particularly worse. 'Sell orders' imples handling sales orders, but then the question was 'where does one go to create an item to sell'? In other words, the 'sell' section is more than just handling sell orders, and sell orders actually forms  a single aspect of the selling activities. Similarly for 'buy orders': these only represent a single aspect of the purchasing activities available. And while its currently the only relevant activity, this section will be expanded on in upcoming and future versions. Hence using the qualifier 'order' on the menu item also doesn't really make sense.

Essentially, 'purchases' and 'sell' as they currently are used provides a good generalized idea of what to expect from each of the menu items, while at the same time reducing the number of alternative possible meanings that may/may not be understood.
