### ISSUE TITLE
V3 - PD doesn't start on Win10 home within VirtualBox

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1758]
**Describe the bug**
Particl Desktop Windows version isn't able to start on Virtualbox.

**To Reproduce**

1. Download: 64bit ISO https://www.microsoft.com/software-download/windows10ISO
2. Install on VB: Win10 Home x64 as the default setting.
3. Set exe properties to "unblock" for smart screen
4. Install PD RC002 Testnet from github
5. Start exe from commandline

**Expected behavior**
Startup possible

**Screenshots**

https://user-images.githubusercontent.com/25568865/103672158-36de2800-4f7c-11eb-8b1b-d3115f0ff3b2.mp4

<img width="1048" alt="Bildschirmfoto 2021-01-05 um 17 37 11" src="https://user-images.githubusercontent.com/25568865/103672534-b66bf700-4f7c-11eb-9967-63e3b96721dc.png">

**Versions (please complete the following information):**
 - Host OS: [e.g. OSX 10.15.7]
 - VirtualBox: [e.g. v6.1.16]
 - Guest: [e.g. Win 10 home x64]
 
**Additional context**
Tested on linux host as well. V2 versions of PD do work.

**Comment by zaSmilingIdiot** [comment]
The zeromq v5 releases have seem some love in the past couple of weeks, and a number of changes and updated releases have meant that the latest zeromq (JS) release of the v5 branch (at this time v5.2.8) contain the fix for this particular issue.

Once  [this](https://github.com/xludx/particl-zmq/pull/2) is merged and a new release of particl-zmq package is made, the fix will be included into both particl-desktop and particl-market. New PD builds should then work correctly across all Windows versions.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
