### ISSUE TITLE
V3 set to delivered items not visible in "all items" orders

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1762]
**Describe the bug**
After an item has marked as delivered it disappears from the list of orders where "all items" is selected by default. Though, the item is indicated with a counter number. Switching the filter to "completed" does show the listing. 

**To Reproduce**
1. Finalze a purchase by marking it "delivered"
2. Item disappears

**Expected behavior**
Keep the item visible when filter is set to "all items" or rename all items to "active orders"?.

**Screenshots**
<img width="1580" alt="Bildschirmfoto 2021-01-09 um 10 08 03" src="https://user-images.githubusercontent.com/25568865/104087925-697d6e80-5263-11eb-8420-279d76541590.png">
<img width="1580" alt="Bildschirmfoto 2021-01-09 um 10 08 15" src="https://user-images.githubusercontent.com/25568865/104087918-64b8ba80-5263-11eb-9627-2c77c12cf7a3.png">

**Versions (please complete the following information):**
- Market 0.3.2
- Core 0.19.1.1
- Client 3.0.0-RC-test002

**Comment by zaSmilingIdiot** [comment]
The completed item is being hidden because the filter "Show inactive and complete" is not checked (and is not checked by default).

In order to preserve the ability to filter out completed items, its helpful to keep the "show inactive and archived" filter option. However, this presents a concern when interacting with the status filters (the "All Items", "Complete", etc options) , as there appears to be some overlap in the concerns. 

The simplest fix/change for now is probably to set the "Show inactive and complete" filter option as being checked/on by default. Which should be updated in the next release.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0 (fix applied as per my previous comment)
