### ISSUE TITLE
Testnet v3. "Learn More" leads to dead page on wiki, Marketplace module

### ISSUE THREAD

**Issue by particularly7** [particl/particl-desktop#1781]
The text "Welcome to marketplace" where you have two options, "explore markets" or "learn more" only appears in full screen mode when opening the market module (inconsistent). Any sort of resizing the window will make this introduction dissapear. 
Clicking on "learn more" leads to a dead link on the particl wiki page (https://particl.wiki/learn/market/)
The right page seems to be https://particl.wiki/learn/market/ but this one is outdated as its first hyperlink describes how to create a "market enabled wallet" over at https://particl.wiki/tutorial/marketplace/intro/, which was only relevant when v2 was live.

**Comment by zaSmilingIdiot** [comment]
Thanks for reporting these. Some feedback:

> The text "Welcome to marketplace" where you have two options, "explore markets" or "learn more" only appears in full screen mode

This is intentional behaviour: the section doesn't fit well into the smaller window size, and necessitates a degree of scrolling to get to the generally common actions. The top information section is not typically utilized, and so adds some "filler" for when the window is made larger. Both links are actually referenced elsewhere in more applicable sections: the "Learn More" is provided for in the Help & Support page of the application, and the "Explore Markets" link is exactly the same as the first block in the Buy section.

> Clicking on "learn more" leads to a dead link on the particl wiki page [...]

Noted, and thank you for pointing this out and finding the correct link.
The wiki link though should probably be updated to cater to all supported versions, so a section in that wiki page should probably be added to indicate usage for PD v3.0 as well. Instructions [on this page](https://particl.wiki/contribute/) seem to indicate that its possible for adding to submit updates to the wiki, if anybody wants to give this a go :)

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
