### ISSUE TITLE
Bulk approval buttons

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1796]
When a seller receives on his listing multiple requests which he all likes to accept, a kind of "bulk accept" button when displaying the filtered "Requesting" items, could be of interest.

Same for the other order states as well. E.g. when you have a bunch of orders in the "packaging" status and you'd like to advance them all together into the "shipping" status.

**Comment by zaSmilingIdiot** [comment]
Is this actually useful though? As in, would a seller not generally want to review each particular sale? For example, to ensure they have sufficient quantity for each and every item, or that it makes sense for them to ship to a particular location, or even legal to do so, etc.

Speaking of, if inventory management and such functionality are added in the future, this is type of bulk acceptance is likely not going to be feasible to implement. Simple example, but if you only have 5 items and there's 3 requests for 4, 2, and 3 items respectfully, it might be feasible to rather make 2 sales to the requests for 2 and 3 items, rather than blindly trying to accept the 4 item request. However, it might instead be better to sell the 4 request if say, the request is a local request rather than the 2 international requests.
What I'm trying to say is that each sale has decisions that we cannot make blind assumptions about. Sure, functionality could be added for when the seller doesn't care about the particular semantics of the sales, but that typically means that either the seller has reviewed each sale to determine that this is the case (in which case, might as well action each item as its being reviewed), or possibly that the only items being sold are something along the lines of digital items (in which case, the buyflow in general should probably be updated as a whole to cater to this type of sale).

Further, the other buyflow steps don't really lend themselves cleanly to catering to bulk actioning either. Mostly the same reasoning as above, but also due to additional details that would typically be ueful at each step; eg: shipping/tracking info.

Hence, I think some additional feedback may be helpful: is this something that would be useful to a number of users?

**Comment by DrDBanner** [comment]
I'd assume something like a checkbox added to a list of requests makes sense though. Check the checkbox on multiple items and execute accept/decline/other in a kind of batch for the user. I haven't the flow in front of me, but I think that's a kind of useful and quite common in lists of events.

**Comment by kangoala** [comment]
Individually checking each order and only checkmarking a checkbox would probably be faster to execute than approving each new order status individually and then having to wait a short moment until you can proceed with approving the next order status. Anyhow, I think this is a nice to have option and not needed to handle with high priority for now. :-)

**Comment by zaSmilingIdiot** [comment]
> [...] that's a kind of useful and quite common in lists of events
> [...] would probably be faster to execute than approving each new order status individually and then having to wait a short moment until you can proceed with approving the next order status

So yes, I understand the concept that it might be faster and more useful. Except, it would be until it isn't: individual events are separate because they have different actions and different consequences. Simple example, in the current flow, but if the bulk action includes items that are being shipped, where does the seller input shipping details (eg: tracking information)? Perhaps a separate form pops up prompting for the different inputs for the different items? But then, what if the seller wants more information on the item to remember which tracking number belongs to which item... which starts becoming clunky. Add in the ability to action multiple different buyflow steps as part of a single bulk action, and we're basically considering a rebuild of the existing layout but with the additional "capturable" info directly in the workflow.

And how to confirm that the user actually did intend to action the item in that way without it being a mistake? Consider the completion of escrow, which commits the seller to the sale: actions like that warrant an additional confirmation.

Thats all assuming that there are not multiple possible actions at each step. Case specifically at the moment is the order requested step in which the seller can either reject or accept. If the seller is considering what action to take as they review each item, then the natural step is to action the item with the decision that was made.

Further, when something occurs that prevents some or all items from being actioned correctly (eg: insufficient funds to accept some requests or to send some smsg, or the wallet becomes locked during the processing), the resulting updating of the user about what went wrong and how to continue it correctly doesn't lend itself naturally to bulk actioning items, particularly when dealing with monetary related matters and where information might be deemed necessary.

Finally, the waiting a short while after each processing would, in the case of a bulk action system, still need to be performed for each order item processed; the waiting time in performing the bulk action step would simply be the sum of the individual order item action waiting times. Assuming no issues with the processing, of course, which circles back to how to encourage the user to continue.

So yep, something to investigate at some point going forward. Just worth understanding whether some solution to this is not going to be worse (more complicated, or error prone,, or ...? ) than the problem its trying to solve.

**Comment by kangoala** [comment]
_"So yep, something to investigate at some point going forward. Just worth understanding whether some solution to this is not going to be worse (more complicated, or error prone,, or ...? ) than the problem its trying to solve."_

100%  👍
