### ISSUE TITLE
Overhaul the product category tree in the Open Market

### ISSUE THREAD

**Issue by btmr** [particl/particl-desktop#1806]
**Is your feature request related to a problem? Please describe.**
I struggle with the product category tree because it doesn't align with most of the lists I am used to from established e-commerce.
New users are likely to check out the open market first and may find the category tree too shallow or confusing. Eg. having a main branch labelled "Electronics" while another is labelled "Cell phones" is contrary to the common experience elsewhere, where "Cell phones" is a sub-category of "Electronics".

**Describe the solution you'd like**
I suggest a product taxonomy that is more in line with what the big e-commerce platforms out there are doing.
We could use what is already openly available, eg. as stated in this article:
https://medium.com/scalia/why-scalia-decided-to-open-source-its-taxonomy-67e0cdf36d7d
https://drive.google.com/open?id=0B-l4QYv5_cVfRnRPQkpULXdUY2s

**Additional context**
In its current form, the product taxonomy of the open market looks like it was an afterthought (shallow tree, "unusal" branching") when it should be making a really good first impression.

**Comment by zaSmilingIdiot** [comment]
The product taxonomy for the open marketplace (and general purpose markets) is specifically provided for in the particl-market service. Please log this issue at: https://github.com/particl/particl-market/issues
Logging it there ensures that attention can be given to it and proper priority assigned to it accordingly, rather than sitting amongst the PD specific issues.

**Comment by btmr** [comment]
Ok, thanks. Issue has been opened at particl-market issues.
I'm closing it here to avoid cluttering particl-desktop issues.
