### ISSUE TITLE
Marketplace will not open Windows 11

### ISSUE THREAD

**Issue by peddles** [particl/particl-desktop#1807]
**Describe the bug**
The marketplace function will not open in Windows 11.  The debug logs show this following error:
2021-09-06T00:14:34Z ERROR: [profiles\DEFAULT\particl-market] ExtKeyImportLoose: Derived key already exists in wallet

**To Reproduce**
 >Install PD on a new Windows 11 machine
 > Wait untill it's fully syncedd
 > Click on the marketplace widget
 > Klik on Market settings
 > Wait for the message "The Particl marketplace failed to start correctly! If you have change some settings recently, try reverting them back"
**Expected behavior**
Load the rest of the options

**Screenshots**
![image](https://user-images.githubusercontent.com/26740163/132197511-2b6d6eae-2af0-4f41-8a20-99f88c0c84df.png)
![image](https://user-images.githubusercontent.com/26740163/132265829-0c231667-5f18-41ed-b0d5-6c8933071e29.png)
![Screenshot 2021-09-08 175011](https://user-images.githubusercontent.com/26740163/132542894-fd536406-7e34-4386-8f80-fec8e60c9e28.png)

**Versions (please complete the following information):**
 - OS: Windows 11 21 h1
 - Particl Desktop: 3.0.0 testnet 005
 - Particl Core: 0.19.2.13

**Comment by zaSmilingIdiot** [comment]
This looks like there might be an issue between a previous testnet version used and the current one. Not something that should apply for the mainnet release.

To fix this particular situation for testnet at least, could you perhaps try the following steps:
#### NB!: take note that its the `testnet` folders that are used, which matters if you have any mainnet instances of any particl services installed on the machine!

1. Using particl-qt or Particl Desktop (the wallet section), find a wallet named "particl-market" and transfer any funds therein to another, non-market related wallet (such as the default wallet")
2. Close PD/particl-qt, and wait for it to close properly. The goal is to ensure that no particl services are running (importantly particl-core is not running).
3. Remove the problematic testnet market related wallets:
    - Open the folder `%UserProfile%\AppData\Roaming\Particl\testnet` ;
    - if there is a folder named 'wallets' then open that;
    - find the folder named 'profiles'  (there should be a single folder inside it named 'DEFAULT' ;
    - delete this 'profiles' folder;
4. Remove the testnet particl-market datastores (which will remove all data related to your testnet particl-market instance)
    - navigate to the folder `%userprofile%\AppData\Roaming\particl-market\testnet`
    - delete the folder named '03'

When restarting PD and the market app/module, its shouldn't now run into this particular error.

**Comment by peddles** [comment]
Hi Arnold,

Indeed  this fixed the issue but how was this possible? my laptop is only a week old and no other testnet versions where installed?

Kind regards

**Comment by peddles** [comment]
I still have a couple of errors left i just noticed i have attached the screenshot

**Comment by peddles** [comment]
> Hi Arnold,
> 
> Indeed this fixed the issue but how was this possible? my laptop is only a week old and no other testnet versions where installed?
update: I still have a couple of errors left i just noticed i have attached the screenshot
> 
> Kind regards

**Comment by zaSmilingIdiot** [comment]
The crux of the problem is that either there's a difference between the actual market related wallets and the stored details for those market related wallets in the particl-market database, or that those market related wallets weren't created correctly to begin with. 

( Noteably, there actually was a 3rd possible situation where the market related wallets were derived from a previously existing wallet named market and would error out if the wallet named 'market' is locked or encrypted at the time. This 3rd scenario shouldn't have been an issue on testnet for the most part, but would apply when people start running this on mainnet... and so this use of a previous wallet was disabled. )

Anyways, the point is that there's a disconnect between what the marketplace service is trying to do with the market related wallets and what can actually be done with them. This steps mentioned earlier basically "reset" the wallet and marketplace state, which lets it cleanly try to start over.
As to how it became an issue to begin with: I'm not 100% certain. Its possible that the MP was launched initially, and then for some reason was shutdown part way through the start up or initialization process. And this happened after the profile wallet was created but before the identity wallet was created (or before the details for the identity wallet could be saved correctly). So the 2nd and subsequent attempts to start the marketplace service failed at this particular step.

There is possibly cause here for updating the particl-market services to better handle its own initialization process (or rather the possible recovery thereof if initializing the marketplace for the first time). However, I don't think this would be a showstopping issue, and for nearly all users except maybe one or 2 unlucky ones, this particular issue won't occur. 
Still, it can and should probably be looked into... but to avoid getting lost in the desktop related issues, this should probably be logged on the particl-market issues list. I'll create one there for this in a little bit.

**Comment by zaSmilingIdiot** [comment]
> > Hi Arnold,
> > Indeed this fixed the issue but how was this possible? my laptop is only a week old and no other testnet versions where installed?
> > update: I still have a couple of errors left i just noticed i have attached the screenshot
> > Kind regards

The errors in the original screenshot are all mostly related to this particular issue. Are there additional or new errors displaying now?

**Comment by peddles** [comment]
I took one more screenshot just an hour ago and attached it to the Original post. Should i come accross more error codes i will forward them.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by peddles** [comment]
Thanks for the elaborate response, if there’s anything i can do please let me know.

Kind regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
