### ISSUE TITLE
Both the particl-market and the default wallet have the same headings at the top.

### ISSUE THREAD

**Issue by elranchowenohava** [particl/particl-desktop#1809]
nothing indicated the wallet was synching while waiting.

I can't right click and just paste the address in.  I have to go cntrl v

I had a balance of about 5 parts.  When I clicked on default wallet, it disappeared.  I had converted it to anon.  I now show 0 parts.  There is nothing in my history about it.

I clicked on Particl Market and it said 8.75 Parts.

I click on Default wallet and it says 0 with nothing in my history.  It goes straight to Particl Market and not to Wallet?    

When I click on particl-market it says wallet overview at the top with 8.75 parts.  

When I click on default wallet it says wallet overview at the top with O total balance.  Both particl market overview and default wallet say Wallet Overview at the top.  Both have different balances.  Is it possible that they should not both be labeled "Wallet Overview"?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. OSX 10.1.4.5 or Windows 10 or Linux Ubuntu 18.10]
 - Particl Desktop: [e.g. v2.2.0]
 - Particl Core: [e.g. v0.18.1.6]

**Additional context**

**Comment by zaSmilingIdiot** [comment]
Thanks for creating the issue... however, I'm a little confused by it and I'm assuming that this includes at least 3 (possibly 4??) different issues? There's also a lot of contextual information missing, which is why the issue template format exists: its really difficult to track down a problem when we first need to try figure out where the problem is to begin with. For future issues, please do try and stick to the issue template format as much as possible, and preferably keep one problem/question/feature per issue created (that way its easy to keep track of what is solved and what still needs to be worked on).

Anyways, here's some attempt at working through this and providing some feedback. Note that this is mostly based on the assumption that these refer to the particl-desktop v3.0.0-RC-test005 version currently released to testnet. If this is instead the v2 particl-desktop client, then please ignore the comments below as it doesn't apply in that case.

Problem 1. There was no indication that the wallet was syncing.
On which view did you note this? When in a specific module/app (eg: wallet/market/governance), the indication of particl-core syncing is displayed in the lower section of the left menu bar when syncing is occurring. However, in saying that, there are 2 scenarios where this can be improved: firstly, when core performs a block header sync (before the actual syncing starts), PD doesn't indicate that this is occurring. Mostly due to PD not being aware of it... however, there is another issue logged already to try and cater to this scenario. The second improvement to be made is on the welcome/landing page: there is no indication of blockchain sync occurring on this page. This should be improved somewhat in a future release with updates to the way PD interacts with core (in terms of startup/shutdown/config options/etc), so this should be improved going forward.

Problem 2: No ability to use a right-click context menu to perform actions like paste (for example: pasting of an address into the wallet app > Send menu option > Receiver's Address field).
Yep, we don't have the right-click context menus anywhere throughout the application at the moment. Its something we can look at adding in the future if its useful to have it.

Problem 3: I understand the following seems to be providing steps of some actions taken, but I'm not sure what the initial balances are for each wallet, nor what the expected outcome is meant to be. I'm assuming that these steps are are also attempting to convey a particular problem that is different from the problem indicated in problem 4 below:
```
I had a balance of about 5 parts. When I clicked on default wallet, it disappeared. I had converted it to anon. I now show 0 parts. There is nothing in my history about it.

I clicked on Particl Market and it said 8.75 Parts.

I click on Default wallet and it says 0 with nothing in my history. It goes straight to Particl Market and not to Wallet?
```

Could this be elaborated on a little please?

Problem 4: The "Wallet Overview" heading should change when the selected wallet changes.
The problem is stated a little differently here than the original, but I suspect that there may be some confusion about the different actions happening.
In PD v3, clicking on the 'Wallets" app/module will present information about the current wallet and allow the user to perform actions specific to the current wallet (such as sending/converting funds, or finding receive addresses, or setting up cold staking, etc). The current wallet is the wallet which is currently selected via the dropdown in the menu on the left side, and would have entries such as "Default Wallet" and "particl-market". Note that last one: this is a wallet with the name "particl-market"... its not the actual particl market services. This particular wallet is created by default by the market service for use with the market services. But because we're specifically dealing with the wallet related activity in the wallet app/module, this allows the user to perform steps necessary for that particl-market specific wallet. In other words, changing between the options "default wallet" and "particl-market" is simply changing the current selected wallet to perform certain wallet-related activities only for the chosen/selected wallet. Hence, the heading of "Wallet Overview" is still applicable regardless of which wallet is currently selected.

For reference, the actual market related activity (buying and selling, etc) is available in the market app/module, and is where the "particl-market" wallet is the default one created by the system for you for use with the market services. It is possibly to create additional wallets for use with the market services as well (and all of these would show up as wallet i the wallet app/module as well for when you want to transfer funds to/from them for example). So by default, when accessing the marketplace app/module for the first time, an additional wallet is created for you for use with that service, and the name of this created wallet is "particl-market".

Hope that helps explain a little bit.
