### ISSUE TITLE
Add notification about antimalware (windows defender) possibly interfering with syncing speed of the blockchain

### ISSUE THREAD

**Issue by particularly7** [particl/particl-desktop#1816]
Particl desktop is a desktop application. For desktop and laptop computers, Windows is the most used at 76% according to a quick google search. With the introduction of a new product, V3, we expect an influx of new users to this beautiful community.

With this in mind, Windows defender is seriously interfering with Particl Desktop, to the point where your average CPU goes up to 80+% capacity and stays there until the blockchain is fully synchronized. On top of that, the blockchain takes at least 4x longer to synchronize because of this deepscan, meaning hours instead of maybe half an hour in a normal environment where antivirus isn't bothering our OS. 

I know this issue is circumstantial and not directly under our influence to be 'fixed' but that doesn't mean we shouldn't at least inform our users which are using Particl for the first time.

I thereby suggest to add something like the following to the blockchain syncing window (note that Particl Desktop is not suggesting here for the user to disable his antimalware necessarily):

**"Antivirus and or malware-detection software run in the background may slow down synchronization speed."**

This issue may seem trivial to you but it's a serious issue nevertheless. If there is anything that prevents a user from using software as intended or severely impacts how one interacts with it, either the software has to be re-designed or the user needs to be informed very explicitly.

_Abanser_ suggested before to have a notification about the issue somewhere in an external guide. Just having a guide (located at a different location than the app itself) which includes such info is not sufficient, efficient in informing and simply not acceptable as someone with a developer background in UX design. It is very important to inform a user **in the application itself**, one cannot expect him to read documentation first, let alone having a clear reason or understanding why he would have to search/read documentation in the first place. In this case, the user may just assume the app is very slow (and possibly get bored, give up). Consulting documentation is mostly only done when experiencing severe issues that prevent the user from moving forward, if the user has not run off already.

Pls, I would hope this very simple 'fix' to be included in the mainnet release, or if anyone has any other suggestion... use this thread

**Comment by zaSmilingIdiot** [comment]
> thereby suggest to add something like the following to the blockchain syncing window 

A message indicating as much has already been added (in the last few days since the RC-test005 release) which will be available in the mainnet release. The message references the location where additional information can be found on possible causes for the slowdown.

> Abanser suggested before to have a notification about the issue somewhere in an external guide. Just having a guide (located at a different location than the app itself) which includes such info is not sufficient [...]
...
> In this case, the user may just assume the app is very slow (and possibly get bored, give up). Consulting documentation is mostly only done when experiencing severe issues that prevent the user from moving forward, if the user has not run off already.

Interesting, because the former sounds exactly like a problem that the latter is meant to resolve. You have to choose a side here... right now you're trying to argue for both sides and you can't have both: the former is a problem that the latter is meant to assist with. As I've mentioned earlier, we've provided reference to documentation that can assist if the user is unsure if there is a problem or not and thinks its slow. But they still have to identify that there may be a problem to begin with (and click on the syncing window to actually see this reference for that matter, implying the start of investigation...). So whether a solution is documented either in-app or at a reference url, some form of documentation has been provided. Since a user is already at this point, the entire troubleshooting guide is going to depend on their specific circumstance... so they are going to have to "read the docs" to try a couple of things that might be relevant to solving their specific situation. And there are many possible causes to the problem, and many potential differing solutions. Are you suggesting that we try to enumerate all of these in the application? Are you suggesting that the user read through all these possible solutions to try and resolve their issue? Oh wait, thats now expecting the user to read some docs.. 😏 
Now, we can try to provide solutions in-app, or via some online reference material. ith the latter solution of providing a reference to online docs it is hands down more up to date, and can be more user friendly, and more relevant and applicable, that trying to put together static troubleshooting guides bundled inside the application, and which potentially don't cater to the exact user's situation if additional context or further information may be needed later.

Essentially, this all breaks down to needing to consider that there are a couple of potential concerns, and even 1 or 2 potential issues may have many possible different solutions. And frankly, as a developer with a background in UX design I'd expect that you would have understood this. As always, context is key and you need to understand the contextual information before throwing weight behind some thought up 5 minute consideration of a solution.

**Comment by particularly7** [comment]
As long as there is some form of reference so user can problem solve (there was none before, which was my point). If download speed is mentioned specifically as an issue (as it seems it will become a very common issue), sure you can refer with a link to documentation

**Comment by zaSmilingIdiot** [comment]
Closing: implemented for mainnet release of v3.0.0
