### ISSUE TITLE
Market admins should be able add custom categories

### ISSUE THREAD

**Issue by mahdi-ln** [particl/particl-desktop#1862]
Market admins should be able add their categories to their market.

**Comment by zaSmilingIdiot** [comment]
Open markets (anybody can sell) use a default category list so as to ensure that buyers have a consistent experience. The category list can quickly become a mess if anyone can create their own categories in this type of market: different spellings for the same category item, multiple of the same types of items in different categories/sub-category structures, etc.

For 'storefront' type markets (where only you, or the people you share the publish key with, can sell items), the seller can most definitely create their own categories. In fact, they need to create at least one category in order to sell anything in their storefront market (after creating a new storefront market, the seller is presented with a prompt to start adding categories, and these can be edited later as well).

In saying that, its still possible to create an open type of market with anybody open to creating their own categories. **_Do note that it is NOT recommended to do this, and this serves more as an indication only of how to achieve what you want_**  : create a storefront type of market, and then instead of only making known the access key you readily hand out the publish key to everybody. This creates a storefront type of market but where anybody can sell on your storefront and thus anybody can create their own categories (so mimicking an open type of market but with everybody having access to creating categories as well).
