### ISSUE TITLE
Particl Desktop precipitates an error when launched in a torified environment.

### ISSUE THREAD

**Issue by ghost** [particl/particl-desktop#1864]
# Bug description

Launching Particl Desktop inside Whonix results in an error as per the attached screenshot.

# To reproduce

1. Install Whonix in a VirtualBox.
2. Download Particl Desktop. Both .zip and .AppImage behave the same.
3. Run Particl Desktop.

# More information

- Operating system: Whonix Workstation
- Client version: Particl Desktop 3.2.2
- Screenshot

![particl_bug](https://user-images.githubusercontent.com/117053906/199157407-d14e82ea-d361-4784-9f9d-c1d06dc08811.png)

**Comment by zaSmilingIdiot** [comment]
Thanks for the report.

In the current Particl Desktop (PD) versions, the Particl Core version is checked at startup of PD, and if necessary (such as during first startup, or when there is a newer Particl Core version available) that Particl Core version is downloaded. Unfortunately, as this happens during PD startup, any failures to correctly start up Particl Core results in PD failing to progress with the application launch. Such issues can be particularly problematic on some distros (like Whonix), particularly since the various services are hosted on Github, which tends to block access to tor exit nodes (as far as I am aware).

We are aware of this though, and the next release of PD (v3.3) is intended to address such concerns. Simple things like having the Particl Desktop fully launch before attempting to process Particl Core related requirements, and then additionally, allowing the user to customize PD's interaction with Particl Core as much as possible. For example, this means that if the Particl Core binary download URLs are inaccessible (not available when routing via tor, for example), the download URL can be changed to one that is more readily accessible, from within the PD GUI. Coupled with additional practical changes (such as hosting Particl Core binaries elsewhere as well), this should likely resolve this particular issue.
