### ISSUE TITLE
install new version results in missing wallet Anon balance

### ISSUE THREAD

**Issue by clayt0nk** [particl/particl-desktop#1875]
The last time I ran Particl Desktop was with version 2.3.5, I just installed 3.3.0 and copied over wallet.dat from the previous 2.3.5 install. Blind balance is correct, but Anon balance is ZERO, and off to the right it says "Pending: 125" PART. 125 is what I was expecting my Anon balance to be. All of the "recent" transactions in the transaction list (the most recent is 2019) claim they are currently unconfirmed, which I am pretty sure was not the case last time I ran this wallet.

This is particl-desktop 3.3.0 running on Ubuntu 20.04.

**Comment by zaSmilingIdiot** [comment]
Restoring a wallet while the blockchain is syncing will typically lead to the case where transactions are displayed but showing them as having 0 confirmations. Once the blockchain syncs past the block height that the transaction occurred in, the confirmations for the past transaction will increase and show as having been completed.

For interest there is also a bug in v3.3.0 in which the balances do not properly update when a new block is found. So this may be compounding the situation. The bug should be fixed in v3.3.1.

**Comment by zaSmilingIdiot** [comment]
v3.3.1 is now available - the corresponding bug mentioned in my previous comment should be fixed with this release

**Comment by clayt0nk** [comment]
My Anon balance has reappeared, thanx.
