### ISSUE TITLE
Finalize GUI Settings page 

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#582]
We need to wrap up the development on the GUI Settings page. Please can we discuss and finalize specification on this issue.

See below screen of design.

![particl_wallet_settings](https://user-images.githubusercontent.com/28799964/34556584-8aefe486-f13f-11e7-8383-98db17094a01.jpg)

**Comment by allienworks** [comment]
Is Settings going to be on a separate page or as a part of Console modal (someone mentioned that earlier)?
What will be included in Settings?

I can start working on it as soon as I have the info.

**Comment by HenkSwardt** [comment]
Hi @allienworks 

This is currently in the GUI but hidden. I believe it has most of what is needed but was done in Angular2. We will need to convert the page to Material first.

**Comment by HenkSwardt** [comment]
@anandsinghparihar will start with the refactoring to Material of the settings page for us. Once this has been completed we will investigate and list all outstanding features on the settings page.

**Comment by anandsinghparihar** [comment]
@HenkSwardt Setting page front-end related work has been done now need any backend developer to complete that that API related stuff (get and set setting), after completing API I'll refactor front-end like all pagination would be dynamically set by settings.

**Comment by zaSmilingIdiot** [comment]
An internal task exists for this.
Given that multiwallets are now implemented in the v2.x implementations, there's a separation of "settings" related information: those that apply to the application as a whole (eg: core related settings), and those that apply specifically to a wallet (eg: whether the market is enabled on it or not).

I believe we need to perhaps re-address the design of this "settings" page to be able to accommodate the distinction. Perhaps even have 2 separate "settings": 
- system configuration
- wallet settings

Thoughts?

**Comment by AllienWorks** [comment]
@zaSmilingIdiot that can be done, no problem. Do we have a overview of all the things that changed between the original PR state and today? I'll be happy to update it (we really need the Settings in place).

**Comment by zaSmilingIdiot** [comment]
No, but I think there has been significant updates. I'm not too concerned with the development work of it -> I was re-working significant chunks of that implementation code at the time anyway. Part of that can be re-used though.

I think the main concern here is separating out what is actually significant in terms of the various settings. For example, indications of whether the side menus start open or closed doesn't seem to be a real concern, and we can add those in if there is a real request for that. More importantly, for example, is adding something like importing wallets via their .dat file, or deleting a wallet, for example (former is likely a "global" setting with the latter likely being a wallet specific one). 

Puerly my personal perspective, but I think it might be a good idea to define the initial required settings properly, and then attempt to salvage what we can from the previous PR, rather than starting with the previous PR and trying to update it retroactively and with new things at the same time.

**Comment by AllienWorks** [comment]
OK, should we summarize the nedded settings in here, JIRA or Paper? We can always start small (what I prefer) and mainly push the Settings page out and then add to it as needed.

**Comment by zaSmilingIdiot** [comment]
Initial settings page has been implemented in v2.2.0

Additional settings can be added as needed, thus I'm indicating this as being resolved.
