### ISSUE TITLE
syncing : show last block time as a timeline

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#590]
When syncing, currently all information is updated every ~10s.
It would be nice that it is updated in real time and show the last block time as a loader / timeline with months and years since 1st block.

**Comment by HenkSwardt** [comment]
@pciavald can I set this to ver 1.2?

**Comment by rynomster** [comment]
It used to update as soon as a block came in. Seems like someone broke it
on dev.

**Comment by allienworks** [comment]
Update in real time: absolutely why not.

Show additional info: I wouldn't add anything more into current UI (let's not clutter it just because we can :). We could show more info in the tooltip on hover – ideally something like "block XX/YY" (current/total); currently there's just numerical % progress to 100%.
