### ISSUE TITLE
syncing indicators too slow

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#798]
When starting the wallet after a week, blocks are being downloaded but it's not visible in the GUI. Syncing more that 5 blocks should trigger the sidebar loader, and current syncing modal pops too late when the amount of blocks to sync is bigger (~30s after starting sync)

**Comment by anandsinghparihar** [comment]
@pciavald I tried but unable to reduce that time, I hope @kewde removing modal service dependency so it will resolve with that.

**Comment by pciavald** [comment]
i would like to make a video but peek is refusing to work right now...

**Comment by zaSmilingIdiot** [comment]
This might actually be possible to be implemented (or at least in a better way) if the application starts the UI first, and then attempts connecting to the daemon afterwards (particularly via zmq).

In such a way, the UI receives a notification of blocks being downloaded, and can thus render the various modals/downloading indicators as needed. This way providing the necessary UI indicators in a timely manner, rather than polling the daemon for the relevant information (which is the cause of the current delay).

Such changes require some restructuring a chunk of the application, which will need to occur after any current restructuring changes have been completed.

**Comment by zaSmilingIdiot** [comment]
Sync notifications now use ZMQ notifications, which more closely aligns with the actual sync processing occuring.

**Comment by zaSmilingIdiot** [comment]
Implemented in release v3.0.0
