### ISSUE TITLE
restructure UX flow

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#860]
- splash screen should manage the select wallet
- inform user on
  - downloading particl
  - upgrade available
- once wallets have been selected .. start daemon
- once RPC connection available goto the main wallet screen
- add an option to view log at this stage (both particl.log and debug.log (if available)) ...

make the splash screen the focal point for the initial interaction

**Comment by zaSmilingIdiot** [comment]
he current wallet interface is derived from a variant of some of the above requested changes.

The daemon is required  to be started though in order to obtain available wallets, unless manual file processing is performed to determine wallets before core has been started. The latter option is not particularly helpful, as there becomes a need to catering for older folder structure formats (along with any future wallet folder structures/layouts), which is error prone and requires duplicate responsibilities.

With that in mind, some of the requested changes are not going to be possible to be implemented at least for the near future, such as the starting of the daemon after the wallet has been selected.
