### ISSUE TITLE
MP Buy and Sell Page: Orders tab, clarify use of buttons and where to display

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#889]
On the history of orders displayed (Bidding, Shipping, Escrow, Sold), when expanded, we have a number of buttons available that does not do anything at the moment. Can we please clarify them.

- [ ] Cancel the order – On what stages will we allow reject or cancel?
- [ ] Edit the order – On what stages will we allow editing an order?
- [ ] Contact Buyer – This will be used for the predefined messages, right?
- [ ] View Payment ID – What will be displayed when clicked?

**Comment by AllienWorks** [comment]
For each stage of the Order, I see it like this (correct me if I'm wrong):
_(Check = show button, unchecked = hide it)_

**Bidding**
- [x] Cancel order ("Reject order/bidding")
- [ ] Edit order (probably not allow, as the Order hasn't been accepted yet..)
- [x] Contact buyer
- [ ] View Payment ID (payment hasn't happened yet)

**Escrow**
- [x] Cancel order (can we cancel during escrow?)
- [x] Edit order (allow, for example if buyer misspelled the address or forgot more quantity of some item..)
- [x] Contact buyer
- [x] View Payment ID (when payment happened)

**Shipping**
- [ ] Cancel order (I won't allow it since items has been shipped already)
- [ ] Edit order (same ^)
- [x] Contact buyer
- [x] View Payment ID

**Sold**
- [ ] Cancel order (can't cancel finalized order)
- [ ] Edit order (don't allow editing after it has been finalized)
- [x] Contact buyer
- [x] View Payment ID

**Comment by HenkSwardt** [comment]
We have resolved this in https://github.com/particl/particl-desktop/issues/914 as part of adding a new status.

Closing as a duplicate.
